= How to use this publication

== Notes, examples and asides

[NOTE]
====
Further explanation, where it may help you to understand concepts or relationships between rules.

You and your opponent are much less likely to dispute or misinterpret rules if you understand why they are written the way they are.
====

[NOTE.option]
====
Notes to highlight an alternative or additional way to play that some players prefer to the default.
If you want to use an option, you and your opponent must both agree.
====

TIP: Advice to help you learn the rules more effectively or get the best out of the game.

IMPORTANT: Reminders about things that are important to get right but easy to miss or forget in the heat of battle.

.Example
====
These boxes contain examples that put rules in context for you, or that show you how to follow the flow of several different rules that work together.
====

.Aside
****
We use these boxes to separate some types of supplemental information from the main text.
****

== Footnotes
Footnotes, for additional information.
footnote:[
We use footnotes like this to present additional information.
In particular, we often use footnotes highlight ways in which {project-name} differs from {e40k}.
]

== Body text styles

`Monospace font with grey background`: We use this mainly to reference characteristic values that we either state on a 'data sheet' or that we bring into effect through a dynamic rule.
For example: Speed `10 cm`; Armour `5+`.

_Italic_ font style: We use this to emphasise a specific 'special ability' or the title of a publication.

== Related information

You'll sometimes see a short list of hyperlinks at the bottom of a topic.
These links are convenient shortcuts to related information that is especially relevant to the topic.
They look like this:

.Related information
* xref:main-rules:data-sheets-and-characteristics.adoc[]
* Experimental: xref:experimental:experimental.adoc[]