= Welcome to the {project-name} project
:experimental:

This is an unofficial project that *reworks* and *extends* the third edition of Games Workshop's _Epic_ game system, _Epic 40,000_.

{project-name} is by fans, for fans, and open to the community as a collaborative effort.

Date of this build: {docdate}

.Proof of concept only!
****
At the moment, this is little more than a proof of concept with some experimental content and minimal styling.

It is mostly an empty outline, but also contains some work-in-progress content:

* Introductory and core rules pages with new wording and somewhat rationalised structure (but no changes to gameplay as yet).
* The start of a possible guide for contributors (to switch between the *E40kR* component and the *Contributor's guide* component see the component menu at the bottom of the navigation panel).

This web output is the only format at this time -- although I have tested and it is easy to compile as an Android app that would afford offline usefootnote:[Or, instead of a native Android app, it should be possible provide offline usage with any modern Web browser via Progressive Web App (PWA) technology -- but I haven't figured that out yet.].
PDF output would involve some tiresome manual steps, but I hope that the underlying technology will evolve to make this much easier in futurefootnote:[This project uses Antora, a static site generator for Asciidoc.].

Some current limitations:

* There is no search function.
However, it shouldn't be too hard to add in future -- working examples exist elsewhere.
* There is no 'relationship table' or 'broken link checker' features for authors, so helpful 'related information' links may pose a challenge for long-term maintenance and consistency.
* The *Edit this page* function is inactive.
I expect it to provide an easy route for people to contribute in future.
* The btn:[Download] button doesn't do anything at the moment, but could direct users to an app or PDF version in future.

Still, this proof of concept serves its purpose as I experiment with it to understand how the technology works and how to integrate it with systems and procedures that will facilitate effective collaboration.

Feel free to discuss this proof of concept in the Facebook group, either in the dedicated announcement or in a separate thread: link:https://www.facebook.com/groups/1952676958177757[+Epic 40,000 Remastered+, window=_blank].

_Eric Weston_
****

.Why do it this way?
****
Speaking from long experience as a professional technical writer: It is usually hard, even exhausting, to deliver and maintain documentation projects.

This is partly because such projects don't scale well, given the inherent complexity and the typical tools and processes that are in use:

* 'More collaborators' doesn't always equate to 'faster and better progress'. Yes, collaboration is great in principle, because you share effort and pool ideas and expertise. But in practice, collaboration also makes it even harder to keep track of work, to ensure consistency and to reach agreement.
* Feedback from the wider community is hard to get and to track in a way that makes it easy to discuss and act upon.
* Even when the writing and editing is 'done', the actual publishing usually involves many labour-intensive steps.

And in spite of all the marketing buzz words, most software for writing projects doesn't actually help much with these challenges.

So, while we could work *hard* with word processors/wikis/forums/whatever, I'd much rather we work *smart*...

To this end, I've been experimenting with technologies that facilitate a zero-cost 'docs like code' approach — see link:https://technology.blog.gov.uk/2017/08/25/why-we-use-a-docs-as-code-approach-for-technical-documentation/[this article on gov.uk, window=_blank] for a general idea of what this means. (The main point is that it becomes much easier to manage content, collaboration and publishing.)

I think that this approach will really help to bring vitality to the project in a way that traditional writing tools and processes just can't.
****