= Welcome to the {project-name} project
:reftext: Welcome
:experimental:

This is an unofficial project that *reworks* and *extends* the third edition of Games Workshop's _Epic_ game system, {e40k}.

{project-name} is by fans, for fans, and open to the community as a collaborative effort.

Date of this build: {docdate}

== Developmental state 

This project is now well under way, but we still have lots to do.

We're not yet ready to treat any part of the project as 'stable' -- we treat all content as 'draft' and subject to change at any moment.
So, we don't spend the time to document the changes (except at a high level as occasional updates in the Facebook group -- see <<Discussion>>).

* Important features are likely to change without notice.
* Styling is minimal.

== Content

The content components in this project are as follows:

* *xref:core::index.adoc[Core]*: The main body of the project.
This is now functionally complete, but there are still improvements we'd like to make and details to attend to.
Among other things, we need to create and add graphics and images -- especially where explanatory examples are concerned.
* *xref:battles::index.adoc[]*: First drafts are in progress in this component, but there are a number of empty placeholder topics at present.
* *xref:armies::index.adoc[]*: Mostly contains empty placeholder topics at present.
But army lists and data sheets are in progress and available in the interactive <<builder>>.
* *xref:contributors-guide::index.adoc[Contributor's Guide]*: Guidance for contributors, to help with governance and consistency, and to document our methods in a transparent way.

TIP: You'll find links to the main components in the main navigation menu.
You can also switch between all components at the component menu (at the bottom of the secondary navigation panel).

Also important to the project, but not held in the same repositories and hosting:

* [[builder]]*link:{uri-builder}[Epic Remastered Detachment Builder^]*: A convenient way to choose your army online and to print out your detachments and unit data sheets.
Ian Wood continues to adapt and extend this from the open source 'Army Forge' software to suit our needs, and to populate it with new and revised content.
We intend that the builder and the _Armies_ component will mirror each other eventually.

TIP: You can also find a link for the builder under the *Resources* item in the main navigation menu.

== Current limitations for usability

* There is no search function yet -- but in January 2023 we completed a software upgrade makes extensions available.
We're testing code to implement a search extension, and we hope to deploy this soon.
* We don't use the *Edit this page* function yet.
We hope to use this in future to provide an easy way for enthusiasts to suggest edits to fix typographical errors, unclear text, and so on.
* The btn:[Download] button doesn't do anything at the moment, but could direct users to an app or PDF version in future.

== Discussion
Feel free to discuss this project in the Facebook group, either in the dedicated announcement or in a separate thread: link:https://www.facebook.com/groups/1952676958177757[EPIC 40,000 Remastered^] (external URL).

== Copyright and licence

include::partial$copyright-and-licence.adoc[]

== Disclaimer

include::partial$disclaimer.adoc[]