= Welcome to the {project-name} project
:experimental:

This is an unofficial project that *reworks* and *extends* the third edition of Games Workshop's _Epic_ game system, _Epic 40,000_.

{project-name} is by fans, for fans, and open to the community as a collaborative effort.

Date of this build: {docdate}

== Developmental state 
This project is now more than a proof of concept, but still very early in development -- perhaps what some would call a *pre-ALPHA* state.

* You'll find some draft content, but much that we will need is missing.
* Important features are likely to change without notice.
* Styling is minimal.

.Why do it this way?
****
Speaking from long experience as a professional technical writer: It is usually hard, even exhausting, to deliver and maintain documentation projects.

This is partly because such projects don't scale well, given the inherent complexity and the typical tools and processes that are in use:

* 'More collaborators' doesn't always equate to 'faster and better progress'.
Yes, collaboration is great in principle, because you share effort and pool ideas and expertise.
But in practice, collaboration also makes it even harder to keep track of work, to ensure consistency and to reach agreement.
* Feedback from the wider community is hard to get and to track in a way that makes it easy to discuss and act upon.
* Even when the writing and editing is 'done', the actual publishing usually involves many labour-intensive steps.

And in spite of all the marketing buzz words, most software for writing projects doesn't actually help much with these challenges.

So, while we could work *hard* with word processors/wikis/forums/whatever, I'd much rather we work *smart*...

To this end, I've been experimenting with technologies that facilitate a zero-cost 'docs like code' approach -- see link:https://technology.blog.gov.uk/2017/08/25/why-we-use-a-docs-as-code-approach-for-technical-documentation/[this article on gov.uk, window=_blank] for a general idea of what this means.
(The main point is that it becomes much easier to manage content, collaboration and publishing.)

I think that this approach will really help to bring vitality to the project in a way that traditional writing tools and processes just can't.

_Eric Weston_
****

== Content
Many of the topics in this project are empty placeholders at the moment.
But there are some early drafts of content in progress, including:

* *E40k Remastered* component: The main body of the project.
At the moment this contains drafts of introductory and core rules pages.
* *E40kR Experimental* component: An area where we can work on more radical ideas.
This will be more loosely controlled than the main body.
* *E40kR Contributor's Guide* component: Guidance for contributors, to help with governance and consistency, and to document our methods in a transparent way.

TIP: To switch between components, use the component menu at the bottom of the navigation panel.

== Output formats
This web output is the only format at this time.

We will likely offer a progressive web app (PWA) in future which would afford offline usage on mobile devices.
Or failing that, a native app for Android.

PDF output would involve some tiresome manual steps, and is far too static to be a good deliverable for a rapidly changing project.
However, when the project reaches a suitable level of maturity and stability then we can can consider a PDF output.
By that time, hopefully the underlying technology will evolve to make PDF output somewhat easier than it would be right nowfootnote:[This project uses Antora, a static site generator for Asciidoc.].

== Current limitations for usability
* There is no search function.
However, we should be able to integrate one soon -- working examples exist.
* There is no 'relationship table' or 'broken link checker' features for authors, so helpful 'related information' links may pose a challenge for long-term maintenance and consistency.
//* The *Edit this page* function is inactive.
//I expect it to provide an easy route for people to contribute in future.
* The btn:[Download] button doesn't do anything at the moment, but could direct users to an app or PDF version in future.

== Discussion
Feel free to discuss this project in the Facebook group, either in the dedicated announcement or in a separate thread: link:https://www.facebook.com/groups/1952676958177757[+EPIC 40K Remastered+, window=_blank].

== Copyright and licence

Copyright 2020 Eric Weston and the Epic 40k Remastered project contributors.

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and limitations under the License.

== Disclaimer

*This publication is completely unofficial and in no way endorsed by Games Workshop Ltd.*

.Trademark list
****
Adeptus Astartes, Battlefleet Gothic, Blood Angels, Cadian, Catachan, the Chaos device, the Chaos logo, Citadel, the Citadel device, Codex, Daemonhunters, Dark Angels, Dark Eldar, the Double-Headed/Imperial Eagle device (Aquila), ’Eavy Metal, Eldar, Eldar symbol devices, Epic, Eye of Terror, Fanatic, the Fanatic logo, the Fanatic II logo, Fire Warrior, Forge World, Games Workshop, Games Workshop logo, Genestealer, Golden Demon, Great Unclean One, Keeper of Secrets, Khemri, Khorne, Kroot, Lord of Change, Necron, Nurgle, Ork, Ork skull devices, Sisters of Battle, Slaanesh, Space Marine, Space Marine chapters, Space Marine chapter logos, Tau, the Tau caste designations, Tyranid, Tzeentch, Ultramarines, Warhammer, Warhammer 40k device, Warhammer World logo, White Dwarf, the White Dwarf logo, and all associated marks, names, races, race insignia, characters, vehicles, locations, units, illustrations and images from the Warhammer 40,000 universe are either ®, ™ and/or © Copyright Games Workshop Ltd, variably registered in the UK and other countries around the world. Used without permission. No challenge to their status intended. All Rights Reserved to their respective owners.
****