= Welcome to the {project-name} project
:experimental:

This is an unofficial project that *reworks* and *extends* the third edition of Games Workshop's _Epic_ game system, _Epic 40,000_.

{project-name} is by fans, for fans, and open to the community as a collaborative effort.

Date of this build: {docdate}

== Developmental state 
This project is now more than a proof of concept, but still very early in development -- perhaps what some would call a *pre-ALPHA* state.

* You'll find some draft content, but much that we will need is missing.
* Important features are likely to change without notice.
* Styling is minimal.

.Why do it this way?
****
Speaking from long experience as a professional technical writer: It is usually hard, even exhausting, to deliver and maintain documentation projects.

This is partly because such projects don't scale well, given the inherent complexity and the typical tools and processes that are in use:

* 'More collaborators' doesn't always equate to 'faster and better progress'.
Yes, collaboration is great in principle, because you share effort and pool ideas and expertise.
But in practice, collaboration also makes it even harder to keep track of work, to ensure consistency and to reach agreement.
* Feedback from the wider community is hard to get and to track in a way that makes it easy to discuss and act upon.
* Even when the writing and editing is 'done', the actual publishing usually involves many labour-intensive steps.

And in spite of all the marketing buzz words, most software for writing projects doesn't actually help much with these challenges.

So, while we could work *hard* with word processors/wikis/forums/whatever, I'd much rather we work *smart*...

To this end, I've been experimenting with technologies that facilitate a zero-cost 'docs like code' approach -- see link:https://technology.blog.gov.uk/2017/08/25/why-we-use-a-docs-as-code-approach-for-technical-documentation/[this article on gov.uk, window=_blank] for a general idea of what this means.
(The main point is that it becomes much easier to manage content, collaboration and publishing.)

I think that this approach will really help to bring vitality to the project in a way that traditional writing tools and processes just can't.

_Eric Weston_
****

== Content
Many of the topics in this project are empty placeholders at the moment.
But there are some early drafts of content in progress, including:

* *xref:core::index.adoc[Core]* component: The main body of the project.
At the moment this contains drafts of introductory, main rules and some special rules content.
* *xref:contributors-guide::index.adoc[Contributor's Guide]* component: Guidance for contributors, to help with governance and consistency, and to document our methods in a transparent way.
* *xref:experimental::index.adoc[Experimental]* component: An area where we can work on ideas, away from the Core component.

TIP: To switch between components, use the component menu at the bottom of the navigation panel.

== Output formats
This web output is the only format at this time.

In future, we should be able to offer offline usage, through progressive web app (PWA) technology -- ideal for your tablet or smartphone.
Or failing this, a native app for Android.

PDF output would involve some tiresome manual steps, and is far too static to be a good deliverable for a rapidly changing project.
However, when the project reaches a suitable level of maturity and stability then we can can consider a PDF output.
By that time, hopefully the underlying technology will evolve to make PDF output somewhat easier than it would be right nowfootnote:[This project uses Antora, a static site generator for Asciidoc.].

== Current limitations for usability
* There is no search function.
However, we should be able to integrate one soon -- working examples exist.
* There are no 'relationship table' or 'broken link checker' features for authors, so helpful 'related information' links may pose a challenge for long-term maintenance and consistency.
//* The *Edit this page* function is inactive.
//I expect it to provide an easy route for people to contribute in future.
* The btn:[Download] button doesn't do anything at the moment, but could direct users to an app or PDF version in future.

== Discussion
Feel free to discuss this project in the Facebook group, either in the dedicated announcement or in a separate thread: link:https://www.facebook.com/groups/1952676958177757[+EPIC 40K Remastered+, window=_blank].

== Copyright and licence

include::partial$copyright-and-licence.adoc[]

== Disclaimer

include::partial$disclaimer.adoc[]