= What you will need, to play
:page-toclevels: 1

Things that you'll need to play the game -- and a few that are nice to have.

If you're an avid tabletop wargame enthusiast then you'll have most of this already.

Otherwise... you might have to borrow, buy or make some of these things.
And, welcome to the addictive world of wargames!
Play for fun, don't sweat the losses and may all your games be jolly and entertaining!

== The big stuff

* An opponent!
{project-name} is primarily a two-player game, with no solo-play rules.
* Two armies of 'Epic scale' miniatures to represent the _Warhammer 40,000_ factions that you and your opponent wish to play.
'Epic scale' is nominally 6 mm or 1:285 scale, but varies somewhat in practice.
* A suitable wargames table to serve as your battlefield.
The 'default' size for Epic games is 180 cm by 120 cm (~6' by 4').
* Miniature terrain/scenery to make your battlefield visually appealing and tactically interesting.

== General accessories

=== Pencil and paper

You don't always need these, but they can be useful to make notes and reminders during the course of a game.
You might also use a pencil and paper-based method to design and record the details of your army between games.

{blank}[TODO: Add something about paper rosters/detachment cards and digital alternatives, especially the link:https://builder.epicremastered.com[Epic Remastered Detachment Builder^].]

=== Measuring device

You'll need to measure distances a lot in the game.
A pair of trusty retractable measuring tapes are ideal.
You'll want ones that have centimetres (cm) marked on them. 

=== Dice

Ordinary six-sided dice.
Wargamers can never have too many, but 20 or 30 is plenty.

=== Damage trackers

You can manage with pencil and paper, but it's nice to have some markers that you can use to track damage (and shields) on some of the larger engines of war in the game.
You might consider:

* Dice of a different size, colour and/or number of faces to your handfuls of ordinary dice.
* 'Damage tracker' or 'wound' dials -- available from many manufacturers, in a range of styles.

== Core rules accessories

You need various visual markers, templates and other aids to track particular effects in the game.

=== Order markers

You need markers to identify the specific orders that you choose for your detachments, and for conditions that are in effect.
(As we explain at xref:main-rules:orders-and-conditions.adoc[].)

.Original Order markers
The original markers that Games Workshop produced for the {e40k} and _Battlefleet Gothic_ games are ideal if you can obtain enough of them (10 or 12 should be enough to play a typical game).
These green six-sided Order markers have a different symbol on each face, and are also known as 'Order dice' for obvious reasons (although we do not use them like dice).

You may be able to source these from the likes of the eBay website -- although they can be expensive as they've been out of production for a long time.

.Alternative Order markers
More likely, you'll need to obtain or create alternatives.
Some ideas:

* The marbled grey six-sided Order markers that exist for the 2016 _Adeptus Titanicus_ game are just as good as the originals, as their symbols are almost identical.
* 3D-printable alternatives exist online, both in six-sided form or as individual tokens for each symbol.
If you don't have access to a 3D printer, there are retailers who sell the physical items.
* Make your own!
Even cardboard squares with text on them will suffice.
{blank}[TODO: We need some nice non- copyright-infringing designs for the order symbols, to use for the graphics in these rules. It'd be great to also add these to a downloadable 'print your own play aids' file.]

=== Blast markers

{blank}[TODO: Add explanation.]

[[barrage-templates]]
=== Barrage templates

These are simply circles of card with a diameter of 60 mm -- originally with colourful artwork to represent explosions.
We recommend that you have three.
Most of the time you need only one, but there are some rare cases where it is helpful to have more at hand.

=== Airfields (aircraft status trackers)

The original {e40k} boxed game included nice printed airfields, to help players to keep track of the readiness of their Flyer units.
These are merely 'nice to have' and are only effective for a small number of flyers anyway.
The main thing is to have a convenient way to keep track of which out-of-play Flyer units are in which state of readiness: Repair; Rearm; Ready.

== Battle-specific accessories

Depending on the nature of the battle that you intend to play in a given session, you may need some of these accessories.

=== Army Morale tracker

You'll need this only when you use the xref:battles:scenario-special-rules:army-morale.adoc[] rules.

{blank}[TODO: Add explanation.]

[[objective-markers]]
=== Objective markers

You'll need these only when you use the xref:battles:scenario-special-rules:objectives.adoc[] rules.

The original {e40k} boxed game included a set of full-colour cardboard objective markers.
These had the name of the objective type on one side and a suitable corresponding graphic on the other.

You could easily create something similar.
Or, it's even better if you create small scenic items to represent them -- it is much more visually satisfying to battle over a miniature bunker or fuel dump than over a cardboard marker!
Just be sure that it's clear what objective type each scenic item represents.

{blank}[TODO: Ideally, in due course we'll add suitable designs to a downloadable 'print your own play aids' file.]

[[hidden-setup-markers]]
=== Hidden Setup markers

You'll need these only when you use the xref:battles:scenario-special-rules:hidden-setup.adoc[] rules.

A set of cardboard or plastic markers will do, so long as each marker has a unique number to identify it.
Eight or ten of these markers will be plenty for most games.

If your numbered markers are small scenic items that represent clusters of foxholes and booby-traps, then so much the better for the visual effect!

[[drop-pods-tokens]]
=== Drop Pods tokens

You'll need these only when you use the xref:battles:scenario-special-rules:drop-pods.adoc[] rules.

Even the original {e40k} boxed game didn't include these (although the _Armies of the Imperium_ expansion for the second edition of Epic did).
But they're easy to make:

. Get some thick paper or thin card.
Photo paper for inkjet printers is a good choice.
. Draw a 1 cm grid, 4 cm by 10 cm, to create 40 squares.
. Use a pen or stamp with permanent ink to number each square, from 1 to 40.
. Cut out your squares -- hey presto, 40 Drop Pods tokens (more than you're ever likely to need at one time).

{blank}[TODO: Ideally, in due course we'll add a suitable design to a downloadable 'print your own play aids' file.]

TIP: You might consider a different material, shape and/or size for your tokens.
As long as you and your opponent use the same tokens then it is fair.
But keep in mind that you'll be dropping these tokens from a height, and these characteristics affect how the tokens typically distribute.
For example, round tokens will sometimes roll across the play area, away from the rest, whilst plastic tokens may bounce and knock miniatures that are in play.

{blank}[TODO: It might be good to suggest optional alternative rules that don't require tokens. Take inspiration from NetEpic perhaps, which developed an alternative procedure in place of the similar token-based rules that existed in 2nd edition.]

[[fortifications]]
=== Fortifications

You'll need these only when you use the xref:battles:scenario-special-rules:fortifications.adoc[] rules.

{blank}[TODO: Add explanation.]

== Fate cards

{blank}[TODO: Add explanation, and link to new Fate cards content when it is ready.]

.Under development
****
We don't have Remastered versions yet, but you can get redrawn versions of the original Fate cards at link:https://thehobby.zone/resources/e40k-compendium/Content/More/FurtherResources.htm[Epic 40,000 Compendium -- Further resources^].]
****

== Reference sheets

{blank}[TODO: Add explanation, and link to new reference sheets when they are available.]

.Under development
****
We don't have Remastered versions yet, but you can refer to xref:more:quick-reference.adoc[].
Or, you can get redrawn versions of the original reference sheets at link:https://thehobby.zone/resources/e40k-compendium/Content/More/FurtherResources.htm[Epic 40,000 Compendium -- Further resources^].]
****