= Table Army Layout 3 in example

Using a table to do layout. In this case its nested in an example to get the outer border, but we could use a custom admonition for this. As it's a table the two-column section doesn't reflow on narrow screens/windows.

====

[cols="1,1"]
[grid=all]
[frame=all]
|===
2+^a|
== *Imperial Guard Infantry detachment*

2+a|
== *Command*

*Detachment base cost: 25 points*

---
You must choose 1-3 command squads.

*Infantry Command Squad:*

* 1 Command Squad _(IG unit)_: 22 points
** *or* Command Squad with Captain _(IG w. Hero)_: 26 points
** *or* Command Squad with Primaris Psyker _(IG w. Psyker)_: 32 points
** *or* Command Squad with Captain and Psyker _(IG w. Hero, Psyker)_: 36 points
* *Add* 1 Chimera: 15 points

---
*Rough Rider Command Squad:*

* 1 Rough Rider Command _(IG w. Assault, Cavalry)_: 24 points
** *or* Rough Rider Command with Captain _(IG w. Assault, Cavalry, Hero)_: 29 points
** *or* Rough Rider Command with Primaris Psyker _(IG w. Assault, Cavalry, Psyker)_: 34 points
** *or* Rough Rider Captain with Psyker _(IG w. Assault, Cavalry, Hero, Psyker)_: 39 points



a|
== *Main Force*
Choose up to *3* squads from the following list for each command squad chosen.

*Imperial Guard Squad:*

* 2 Imperial Guard units: 14 points
** *or* 1 Imperial Guard unit and 1 Imperial Guard unit w. Commissar _(IG unit w. Hero)_: 18 points
* *Add* 1 Chimera: 15 points

---
*Imperial Guard Heavy Weapon Squad:*

* 1 Heavy Weapon unit _(IG w. Heavy Weapons)_: 15 points
** *or* 1 Heavy Weapon unit w. Commissar _(IG w. Heavy Weapons, Hero_): 19 points
* *Add* 1 Chimera: 15 points

---
*Rough Rider Squad:*

* 1 Rough Rider unit _(IG w. Assault, Cavalry)_: 9 points

NOTE: Rough Riders as a Main Force choice require at least one Rough Rider Command.

a|
== *Support*
Make up to *9* choices from the following list, but you may not exceed the number of choices made on the Main Force list.

*Imperial Guard Squad (Support):*

* 2 Imperial Guard units: 14 points
** *or* 1 Imperial Guard unit and 1 Imperial Guard unit w. Commissar _(IG unit w. Hero)_: 18 points
* *Add* 1 Chimera: 15 points

---
*Imperial Guard Heavy Weapon Squad (Support):*

* 1 Heavy Weapon unit _(IG w. Heavy Weapons)_: 15 points
** *or* 1 Heavy Weapon unit w. Commissar _(IG w. Heavy Weapons, Hero_): 19 points
* *Add* 1 Chimera: 15 points

---
*Rough Rider Squad (Support):*

* 1 Rough Rider unit _(IG w. Assault, Cavalry)_: 9 points

---
*Ratling Squad:*

* 1 Ratling unit _(IG w. Infiltrators)_: 8 points

---
*Ogryn Squad:*

* 1 Ogryn unit: 11 points

---
*Sentinel Squadron:*

* 1-5 Sentinels: 10 points each

---
*Support Weapon Battery:*

* 1-3 Support Weapons: 21 points each

---
*Leman Russ Battle Tank:* 33 points

---
*Demolisher Support Tank:* 22 points

---
*Griffon Mortar:* 20 points

---
*Hellhound Flame Tank:* 15 points

---
*Hydra Flak Tank:* 25 points

2+a|
_**Chain of Command:** Captain > Command Squad > Any unit with a Commissar > Imperial Guard unit/Heavy Weapon unit/Rough Rider unit > Any other unit._

|===

====