= Snap Fire

A unit that strays too close to enemy units may fall prey to opportunistic fire, traps or prepared ambushes.
We represent the effects of this with the *Snap Fire* rule.

During the Movement phase *only*, if your opponent moves a unit such that it passes within 10 cm of one of your units then you may make a Snap Fire attack:

NOTE: This is a special type of attack, and normal shooting rules -- such as line of sight and Firepower -- do not apply.
footnote:[
Snap Fire represents various forms of attack that come into effect at such short range, such as booby traps or ambush.
The main point is that you should position your units to make the best use of the Snap Fire rule, such that you limit enemy movement.
Then your opponent must either avoid your detachment or try to force a way through with shooting and/or an assault.
]

IMPORTANT: To be absolutely clear: You may declare Snap Fire attacks in the Movement phase only -- you may not declare Snap Fire attacks against units that move in the Assault phase.

. Declare your intent to make a Snap Fire attack immediately, before your opponent proceeds to move other models.
. Your opponent must 'backtrack' to place the unit at the point where it first comes within 10 cm of one of your units.
The sudden attack brings it to a halt there -- your opponent may not move that unit any further in this phase.
+
{blank}[TODO: What if this was the first move in a triple move under March orders? Should the enemy lose the rest of their entire move for the phase, or only the rest of that one move?]
. Roll a D6 to resolve the attack: If you score equal to or higher than the enemy unit's Armour value then it takes a hit.
include::partial$effect-of-hits.adoc[]

Note these conditions:

* You may Snap Fire with an individual unit any number of times in a single turn -- but no more than once at a particular target.
* As long as the target unit survives then Snap Fire does not affect its ability to act later in the turn -- it can act as is usual for the orders under which it is operating. 
* In the event that an enemy unit is already within 10 cm at the start of its move in the Movement phase, then you may Snap Fire at it only if it moves closer.
You may not Snap Fire at it if it remains where it is or it moves farther away.
+
{blank}[TODO: In effect, as Snap Fire halts movement anyway, your opponent cannot move the unit closer in the Movement phase unless either you are daft enough not to take the opportunity to apply the Snap Fire rule, or they are daft enough to needlessly grant you that opportunity!]

{blank}[TODO: Can we ditch the Snap Fire rule for most purposes, and replace it with a rule like the 'zone of control' in _Epic Armageddon_? After all, the general effect of Snap Fire is that players don't move units to within 10 cm anyway. Of course, we would still need Snap Fire in some form where flyers and Flak are concerned.]