= Formats of this publication

To make this publication as user-friendly as possible across all formats, we use 'web-first' writing techniques rather than traditional 'print-first' techniques.

Right now, this website is the only output format for this publication -- but we're testing functionality that will allow us to also publish other formats every time we publish updates to the content.
The idea is to *automatically* provide up-to-date PDF files (mainly for those who want to print physical copies) and an installable app that has offline functionality (so that you can consult the rules even when you have no Internet access).

.About the publishing toolchain
****
In case you're geeky enough to be interested:
This project uses Antora, a static site generator for the Asciidoc plain-text markup language, and GitHub Actions, to deploy updates to the website with very little effort.

We'll use additional extensions and scripts to publish PDF files and progressive web app (PWA) functionality with dynamic caching.

This is non-trivial, but if we can get it working to a satisfactory level then it becomes easy to deliver these extra formats.
Otherwise, these extra formats would demand a lot of additional manual effort to produce -- not just once, but every time there is an update -- and I don't consider that to be a good use of time, especially while the content in this project is still undergoing significant change.

-- _Eric Weston_
****