= Holo-fields

{unit-ability}

This unique technology projects a field that can hide an Eldar titan in a colourful but diffuse and baffling appearance.
This makes it almost impossible for the enemy to pinpoint the precise location of the titan -- it can thwart even the most advanced targetting systems.

However, Eldar titans are of light construction -- they are built for speed and agility, not resilience.

---

Where your unit has the {holo-fields} ability:

* Each time the unit suffers a hit, from any source, roll a die for a {holo-fields} save:
 ** *2+*: Successful save, ignore the hit -- it causes no damage.
 (But place Blast markers as normal.)
 ** *1*: Unsuccessful save, apply the hit as normal.
* Any time that you must apply a hit to the unit, your opponent also *automatically* gets to roll on the Critical Damage table on the data sheet for your unit.
+
If the hit comes from an attack that would normally cause automatic critical damage anyway, there is no added effect -- your opponent gets only the one roll on the table, per hit.

NOTE: While some attacks ignore void shields and power fields, these do *not* ignore holo-fields.