= Shooting at war engines

Resolve shooting at War Engine detachments in much the same way as for other detachments -- there are just a few more details to consider.

== War Engine detachments and the Firepower table

The Firepower table includes target categories especially for War Engines and for Immobilised War Engines.
These categories reflect the fact that these units are so large and easy to hit.

* A War Engine unit can become Immobilised -- and so even easier to hit -- as a result of *critical damage*.
* There is no target category for 'Immobilised War Engine in the open' -- instead, you simply roll as many attack dice as the resultant Firepower that you direct at the unit.
* If a target detachment contains both mobile and Immobilised War Engine units, then you may choose to shoot at only those that are Immobilised, if you wish.
If you do this then you may allocate hits to the Immobilised units *only*.

== War Engine units and Damage Capacity

Unlike other units, War Engine units can absorb more than one hit before they are destroyed.

Each War Engine unit has an initial Damage Capacity value on its data sheet, which shows how many hits it can take before it is destroyed.
Each unsaved hit reduces the current Damage Capacity of the War Engine unit by one point.
The unit is destroyed only when its current Damage Capacity value reaches zero.

[TIP]
.How to keep track of damage
====
To keep track of remaining Damage Capacity on each damaged War Engine unit you might simply keep notes on a piece of paper.
Or, you may like to use coloured dice or 'damage tracker' dials -- when a War Engine takes damage, place a die or dial near it at the correct value to show the remaining Damage Capacity for that unit.
====

== Allocation of hits in War Engine detachments

Where the target detachment consists of more than one War Engine unit, allocate hits in the usual way.
So, allocate one hit to the nearest available target unit, then the next nearest, and so on.

.Related information
* xref:war-engine-critical-damage.adoc[]