= Skimmer

{unit-ability}

These units have technology that allows them to hover just above terrain and 'skim' over it as they move.
They can also boost their ground clearance for short periods, to clear trees, buildings and other tall terrain, or to pop up and shoot at enemy units that would otherwise be out of sight.

---

Where your unit has the {skimmer} ability:

* When you move the unit, you may ignore terrain -- though you must still take a dangerous terrain test whenever the unit starts a move in dangerous terrain, and whenever it ends a move in dangerous terrain.
And you still may not place the unit on impassable terrain.
* In the Shooting phase, you may make a 'pop-up' attack with the unit.
In such an attack, the unit rises up so that it can see over intervening terrain and target an enemy that lies beyond.
** When you make a pop-up attack with the unit, you can draw a line of sight over intervening terrain.
** The unit remains 'popped up' for the remainder of the Shooting phase -- it returns to ground level at the end of the phase.
In the meantime, your opponent can also draw a line over intervening terrain to shoot back.