= Tunneller

{unit-ability}

{blank}[TODO: add introductory text.]

---

Where your unit has the {tunneller} ability:

{blank}[TODO: Need to check the detail and structure of these points against the drop pod rules and the Planetary Assault scenario rules.]

* Treat these units just like Drop Pods, except replace each Drop Pods token on the tabletop with the corresponding {tunneller} unit.
** You can then use the {tunneller} units just as you would for any other detachment.
** As with Drop Pods, make sure that you clearly indicate which cargo units are embarked in which {tunneller} transport units before you deploy them.
* Like Drop Pods detachments, detachments of {tunneller} units always count as Reserves.
* In Planetary Assault scenarios: {tunneller} units do *not* count as Drop Pods, but you may deploy them with their free transport vehicle.

.Related information
* xref:battles:scenario-special-rules:drop-pods.adoc[]
* xref:battles:scenario-special-rules:reserves.adoc[]
* xref:battles:scenarios:battle-6-planetary-assault.adoc[]