= War engine movement

The sheer mass of a war engine makes it lumbering and slow to manoeuvre.

---

== Forward movement of War Engine units

In general, when you move a War Engine unit, you may only move it in a straight line, directly ahead.
However:

* You may make a single turn of up to 45° for free as part of the move.
* You may make more turns, at a cost of 5 cm of the unit's move per extra turn of up to 45°.

.Forward movement of War Engine units
====
{blank}[TODO: Diagram needed.]

You wish to engage some Space Marine units before they can reach the cover of woods and flank your Ork Great Gargant.
You want to manoeuvre your Gargant towards the Space Marines, around the woods.
It has a Speed value of `15 cm`.
You move it as follows:

. Forward 5 cm, then a free 45° turn.
. Forward 5 cm, and then another 45° turn which costs the last 5 cm of the Gargant's movement.
. Now the Gargant is in the perfect position to blast the Space Marines with its ranged weapons!
+
{blank}[TODO: Should we mention Snap Fire here, to be absolutely clear? Or make the graphic such that the Gargant clearly isn't within 10 cm, so this doesn't come up?]

Another option would be to make the free 45° turn at the start, and move up to 15 cm straight towards the Space Marines, through the woods.
But then you would have to take your chances with a dangerous terrain test.
====

== Reverse movement of War Engine units

You may move a War Engine unit backwards, though not as fast.
Make the move in the same way as for forward movement, except that you may not move the unit more than 5 cm.

== Movement of War Engine units in the Assault phase

In the Assault phase, you may choose *not* to move units in a War Engine detachment -- but then you may not initiate close combats or firefights with them either.
Otherwise, War Engine units are subject to the same movement restrictions in the Assault phase as other units, but their own movement restrictions take priority.

== War engine units and dangerous terrain tests

Where appropriate, you must make a dangerous terrain test with a War Engine unit, just like any other unit.
The effects of a failed test are the same, but note that if the War Engine suffers a hit there is no chance that it will inflict critical damage.

{blank}[TODO: At the moment, the dangerous terrain test topic includes a note about the 'no chance of critical damage' point. Should we remove it from there, or leave it as a reminder? Strictly, it is part of the advanced rules, but perhaps this is a case where some overlap is okay, especially given that the terrain table lists effects on War Engine units.]

.Related information
* xref:main-rules:terrain-effects-on-movement.adoc#dangerous-terrain-test[Dangerous terrain test]
* xref:war-engine-critical-damage.adoc[]