= Barrage

These weapons can saturate a wide area of the battlefield with intense salvoes or giant explosions.

---

TIP: The more closely packed the units of the target detachment, the more effective {barrage} weapons are likely to be against it.
This is simply because the barrage will have more target units within its area of effect.

//+[IJW editing note: I've changed this to plural as you almost always have multiple barrage weapons being resolved at once.]+

When you shoot with a detachment that includes units with {barrage} weapons:

. Place a single Barrage template over the target detachment, no matter how many {barrage} units in your detachment are firing at them.
. Place the template so that it:
* is completely within range and line of sight of all units contributing to the {barrage}
+
NOTE: Units with {artillery} *and* {barrage} do not need line of sight to the template.
* covers as many units as possible from the target detachment.
. Who is covered by the template?
* Infantry units (INF) if the centre of their base is under the template.
* Vehicle units (VEH) and war engine units (WE) if any part of their base is under the template.
. The number of covered enemy units from the target detachment is the Firepower value for each {barrage} unit contributing to the attack.
. Add this to the total Firepower that the detachment brings to bear on the target detachment.

IMPORTANT: For the placement of Blast markers, count a {barrage} shot along with regular Firepower and not as a super-heavy weapon.

.A classic {barrage} unit
====
The Space Marine Whirlwind armoured vehicle is armed with a Whirlwind missile launcher.
What this vehicle lacks in range it can make up for in speed and the ability to rain a destructive barrage of missiles down onto an area of the battlefield.
====

.Adding up Firepower
====
Three Space Marine Whirlwinds are firing at an Ork detachment.

* The Space Marine player places one Barrage template, which covers three Ork  Infantry and an Ork Vehicle.
* Each Whirlwind therefore adds 4 Firepower to the Space Marine detachment's Firepower.
====