= Cavalry

Despite the abundance and variety of technologies in the galaxy of the 41^st^ millennium, armies still find uses for cavalry -- and not only on the most barbaric worlds.

Of course, riders and their mounts vary enormously -- humans on horses, denizens of Chaos on daemonic steeds, orks on cyboars, and many more.

---

Where your unit has the {cavalry} ability, apply these changes relative to their base unit:

* The unit has a split Speed value. The first value is double the base unit's Speed value and the second is triple the base unit's Speed value.
* The unit type is Vehicle.

.{cavalry} data sheet modifiers
====
An Imperial Guard Rough Rider unit is an Imperial Guard unit with the {cavalry} ability.

* The base unit's Speed value of 10 cm becomes 20/30 cm.
* The base unit's unit type changes from Infantry to Vehicle.
====

[NOTE.e40k]
====
In comparison to _Epic 40,000_, we've separated the Armour bonus part of {cavalry} into the {armour-1} ability.
====


.Related information
* xref:main-rules:data-sheets-and-characteristics.adoc[]
* xref:main-rules:units-and-unit-types.adoc[]
* xref:main-rules:assault-moves-and-charges.adoc[]
* xref:armour-1.adoc[]
