= Cavalry

Despite the abundance and variety of technologies in the galaxy of the 41^st^ millennium, armies still find uses for cavalry -- and not only on the most barbaric worlds.

Of course, riders and their mounts vary enormously -- humans on horses, denizens of Chaos on daemonic steeds, orks on cyboars, and many more.

Cavalry forgo some of the advantages of infantry -- they find it difficult to take cover, to move through buildings or rubble, and so on.
But they make up for this with speed.

[NOTE.e40k]
====
In comparison to _Epic 40,000_, we've separated the Armour bonus part of the _Cavalry_ ability into our new {armour-1} ability.
====

---

Where your unit has the {cavalry} ability, apply these changes relative to its base unit:

* Change its Speed value to double (2x) that of the base unit.
* Apply the effects of the {swift} ability on this new Speed value:
 ** For a charge move only, you may increase the Speed value of the unit by 50% (1.5x).
* Change the unit type to Vehicle (VEH).

.{cavalry} data sheet modifiers
====
An Imperial Guard Rough Rider unit is an Imperial Guard unit with added special abilities.
The {cavalry} ability means that:

* While the base unit has a Speed value of `10 cm`, that of the Rough Riders is `20* cm`.
The {swift} ability means that for a charge move the unit will have a Speed value of `30cm`.
* While the base unit has a unit type of Infantry (INF), that of the Rough Riders is Vehicle (VEH).
====

.Related information
* xref:main-rules:data-sheets-and-characteristics.adoc[]
* xref:main-rules:units-and-unit-types.adoc[]
* xref:main-rules:assault-moves-and-charges.adoc[]
* xref:armour-1.adoc[]