= Cavalry

`Data sheet modifier`
footnote:[{e40k-diff}
We've shifted the Armour bonus part of {e40k}'s _Cavalry_ ability to a separate ability that we call {armour-1}.
]

Despite the abundance and variety of technologies in the galaxy of the 41^st^ millennium, armies still find uses for cavalry -- and not only on the most barbaric worlds.

Of course, riders and their mounts vary enormously -- humans on horses, denizens of Chaos on daemonic steeds, orks on cyboars, and many more.

Cavalry forgo some of the advantages of infantry -- they find it difficult to take cover, to move through buildings or rubble, and so on.
But they make up for this with speed.

---

Where your unit has the {cavalry} ability, apply these changes relative to its base unit:

* Make its first Speed value two times (2x) the *first* Speed value of the base unit.
footnote:split-speed[
include::main-rules:partial$charge-moves-split-speed.adoc[]
]
* Make its second Speed value three times (3x) the *first* Speed value of the base unit.
footnote:split-speed[]
* Change the unit type to Vehicle (`VEH`).

.{cavalry} data sheet modifiers
====
An Imperial Guard Rough Rider unit is an Imperial Guard unit with added special abilities.
The {cavalry} ability means that:

* While the base unit has a Speed value of `10/20 cm`, that of the Rough Riders is `20/30 cm` -- that is, `(10 x 2)/(10 x 3) cm`.
* While the base unit has an Armour value of `3+`, that of the Rough Riders is `4+`.
* While the base unit has a unit type of Infantry (`INF`), that of the Rough Riders is Vehicle (`VEH`).
====

.Related information
* xref:main-rules:data-sheets-and-characteristics.adoc[]
* xref:main-rules:units-and-unit-types.adoc[]
* xref:main-rules:assault-moves-and-charges.adoc[]
* xref:armour-1.adoc[]