= Flak

These units are specialised to shoot down enemy flyers and drop pods.
Some use very sophisticated targeting devices and fast, accurate weapons systems.
Others simply fill the air with so many munitions that they can hardly fail to get some hits.

---

{flak} units can attack flyers in one of two different ways, depending on what orders you give to their detachment.

[IMPORTANT]
.Flak and drop pods
====
{flak} units may fire on drop pods as if they were flyers, against the Armour value of the transported unit.
====

== Flak orders
For optimum effectiveness, {flak} units and their detachment need to be at a suitable state of readiness.
We represent this state with special orders called Flak.

. If you wish to place any detachments on Flak orders, you must do this in the Start phase.
+
[TIP]
====
You can place a detachment on both Flak orders and Preparatory Bombardment orders at the same time in the Start phase, if you wish, declaring both at the same time.

In this case, you will be able to make a Preparatory Bombardment with {artillery} units in the detachment, and make Flak attacks with {flak} units.
====
. Place the {special-orders} marker to indicate that the detachment is on Flak orders.
. You can use these units to shoot at flyers in the movement phase.
+[TODO: ...and at drop pods? The errata mentions that they can Snap Fire at 'flyers and drop pods' in the 'other orders' bit of text, seemingly as an afterthought -- seems to imply that they should be able to target drop pods while on Flak orders too.]+
+[IJW: It's not spelled out in the original Flak rules, because it's in the drop pod rules. However, see the IMPORTANT box I've added at the top, which spells out that Flak units treat drop pods as flyers.]+
 * You may not move the units in the Movement phase, nor use them to shoot in the Shooting phase.
 * Treat the other units in the detachment as though they are on Overwatch orders -- so you can move them up to 5cm in the Movement phase and re-roll misses when you shoot with them in the Shooting phase.
. {flak} units can shoot at enemy flyers if any part of their flight path is within the {flak} unit's full Range:
 * Roll one D6 for each point of the {flak} unit's Firepower.
 Each result that is equal to or higher than the flyer's Armour value scores a hit on the flyer.
 You can split the firepower of the {flak} unit between several flyers if you wish.
 * Once you have rolled a D6 for each point of the unit's Firepower, the unit cannot shoot for the rest of the turn.
 * You can apply the effects of super-heavy weapons. +
.Flak, with a super-heavy weapon
====
The Eldar Fire Prism has a single {macro-weapon} attack.
This means that you will roll one die, and you'll hit on a result of 4+ — regardless of the flyer's Armour value.
====
 +[TODO: Should we unify this with the usual hit allocation rules? Seems like we should clarify special abilities too, eg {macro-weapon} which is mentioned in the errata for the alternative Snap Fire attack but not in the main part of the Flak rules.]+
 +[IJW: As far as I can see, the Flak unit gets to choose targets freely, and yes MW works when on Flak orders.]+

== Any other orders
Apply these rules to the unit's Snap Fire attacks against flyers:

* Use the {flak} unit's full Range, instead of the usual 10cm.
+
NOTE: Super-heavy weapons such as {macro-weapon} cannot be used for Snap Fire attacks.


+[TODO: So, in effect we have to fall back on the Firepower value that would apply? Presumably not the 'base unit' Firepower, but the 'fallback from a super-heavy weapon to FP1 by default' Firepower of 1 that we see in other cases such as firefights? So, we'd count a Fire Prism as FP1 in this case, and therefore get 1 Flak shot?]+
+[IJW: This isn't relevant, Snap Fire is always a single shot regardless of Firepower.]+

.Flak attacks
====
+[TODO: New example text and image needed]+
====

*Related information*

* xref:battles:drop-pods.adoc[]
