= Flyers and Flak

You can't just shoot at airborne flyer units in the same way that you shoot at ground units.
You must use units that have the {flak} ability in the manner that we explain here.

[NOTE.e40k]
====
We made these rules fit with the new Start phase.
====

---

{flak} units can attack flyers in one of two different ways, depending on what orders you give to their detachment.

[NOTE]
.Flak and drop pods
====
{flak} units may also shoot at units that use the Drop Pods rules, as if they were flyers.
For your rolls to hit, use the Armour value of the cargo unit.
====

== Flak, with Flak special orders
For optimum effectiveness, {flak} units and their detachment need to be at a suitable state of readiness.
We represent this state with special orders called Flak.

Declare the Flak orders::
. If you wish to place any detachments on Flak orders then you must do this in the Start phase.
+
[TIP]
====
You can place a detachment on both Flak orders and Preparatory Bombardment orders at the same time in the Start phase, if you wish.
You must declare both at the same time.

In this case, you will be able to make a Preparatory Bombardment with {artillery} units in the detachment, and make Flak attacks with {flak} units.
====
. Place the {special-orders} marker to indicate that the detachment is on Flak orders.
. You can use these units to shoot at flyers in the movement phase.
 * You may not move the units in the Movement phase, nor use them to shoot in the Shooting phase.
 * Treat the other units in the detachment as though they are on Overwatch orders -- so you can move them up to 5 cm in the Movement phase and re-roll misses when you shoot with them in the Shooting phase.

 Make Flak attacks::
. You can use a {flak} unit to shoot at enemy Flyer units in the Movement phase if any part of their flight path is within the {flak} unit's full range:
* Do not use the Firepower table.
Roll one D6 for each point of the {flak} unit's Firepower value.
Each result that is equal to or higher than the Flyer unit's Armour value scores a hit. (See xref:hits-on-flyers.adoc[])
+
NOTE: You can split the firepower of the {flak} unit between several target Flyer units if you wish.
+
* Or, where your {flak} unit has a super-heavy weapon, you can apply the effects as normal.
* Once you have rolled a D6 for each point of the {flak} unit's Firepower, or you've used all of its super-heavy weapon shots, you cannot shoot again with this unit for the rest of the turn.

{blank}[TODO: This wording implies the player could split {flak} unit firepower between multiple waves of flyers in the phase. Is this intended and important? If not, then it'd be simpler to phrase and to track in-game if we say that once you've made a Flak attack with a unit you can't shoot with it again that turn.]

{blank}[IJW reply: Yes this appears to be intended, and is definitely important. If you weren't allowed to hold back shots then a small sacrificial detachment could 'clear out' a corridor through the Flak before your heavier Flyers arrive.]

{blank}[IJW reply: I've expanded the super-heavy weapon reference to include 'shots', as there may be future WE weapon mounts that count as being on Flak orders and have more than one super-heavy weapon shot.]

.Flak, with a super-heavy weapon
====
The Eldar Fire Prism has a single {macro-weapon} shot.
This means that you will roll one die, and you'll hit on a result of 4+ — regardless of the flyer's Armour value.
====

== Flak, with any other orders
Apply these rules to the unit's Snap Fire attacks against flyers in the Movement phase:

* Use the {flak} unit's full range, instead of the usual 10cm.
Resolve hits as at xref:hits-on-flyers.adoc[].
+
NOTE: You may not use super-heavy weapon effects -- such as {macro-weapon} -- for Snap Fire attacks.

.Flak attacks
====
+[TODO: New example text and image needed]+
====

.Related information
* xref:flak.adoc[]
* xref:battles:drop-pods.adoc[]