= Flyers and Flak

You can't just shoot at airborne flyer units in the same way that you shoot at ground units.
Instead, ground units can Snap Fire as the flyer units move overhead.
Units that have the {flak} ability can do so more effectively, as we explain here.

[NOTE.e40k]
====
We updated these rules to fit with the new Start phase.
====

---

{flak} units have two levels of effectiveness when attacking flyers, depending on what orders you give to their detachment.

[NOTE]
.Flak and drop pods
====
{flak} units may also Snap Fire at units that arrive use the Drop Pods rules, as if they were flyers.
For these Snap Fire attacks, use the Armour value of the cargo unit and roll each die once to hit -- you do not need to roll the die a second time to see how badly you damage the target.

{blank}[IJW editing note: I've expanded this to make it clearer that you're making a 'regular' Snap Fire attack, with no need to roll again to damage/destroy.]
====

== Flak, without Flak special orders
Apply these rules to the unit's Snap Fire attacks against flyers in the Movement phase:

* Use the {flak} unit's full range, instead of the usual 10cm.
+
NOTE: You *cannot* use super-heavy weapon effects -- such as {macro-weapon} -- for normal Snap Fire attacks.

== Flak, with Flak special orders
For optimum effectiveness, {flak} units and their detachment need to be at a suitable state of readiness.
We represent this state with special orders called Flak.

Declare the Flak orders::
. If you wish to place any detachments on Flak orders then you must do this in the Start phase.
+
[TIP]
====
You can place a detachment on both Flak orders and Preparatory Bombardment orders at the same time in the Start phase, if you wish.
You must declare both at the same time.

In this case, you will be able to make a Preparatory Bombardment with {artillery} units in the detachment, and make Flak attacks with {flak} units.
====
. Place the {special-orders} marker to indicate that the detachment is on Flak orders.
. You can use these units to shoot at flyers in the movement phase.
* You may not move the units in the Movement phase, nor use them to shoot in the Shooting phase.
* Treat the other units in the detachment as though they are on Overwatch orders -- so you can move them up to 5 cm in the Movement phase and re-roll misses when you shoot with them in the Shooting phase.

Make Flak attacks::
Apply these rules to the unit's Snap Fire attacks against flyers in the Movement phase:

* Use the {flak} unit's full range, instead of the usual 10cm.
* You can make one Snap Fire attack for each point of the {flak} unit's Firepower value, or for each super-heavy weapon shot.
** You can split these Snap Fire attacks between several target Flyer detachments if you wish.
** Once you have made a Snap Fire attack for each point of the {flak} unit's Firepower, or each of its super-heavy weapon shots, you cannot shoot again with this unit for the rest of the turn.
+
NOTE: You *can* use super-heavy weapon effects -- such as {macro-weapon} -- for these Snap Fire attacks.

{blank}[TODO: This wording implies the player could split {flak} unit firepower between multiple waves of flyers in the phase. Is this intended and important? If not, then it'd be simpler to phrase and to track in-game if we say that once you've made a Flak attack with a unit you can't shoot with it again that turn.]

{blank}[IJW reply: Yes this appears to be intended, and is definitely important. If you weren't allowed to hold back shots then a small sacrificial detachment could 'clear out' a corridor through the Flak before your heavier Flyers arrive.]

---

.Flak special orders, with a super-heavy weapon
====
The Eldar Fire Prism has a single {macro-weapon} shot.
This means that you will roll one die, and you'll hit on a result of 4+ — regardless of the flyer's Armour value.
====

.Flak attacks
====
+[TODO: New example text and image needed]+
====

.Related information
* xref:flak.adoc[]
* xref:battles:drop-pods.adoc[]
* xref:main-rules:snap-fire.adoc[]