= Has +{super-heavy weapon}+

`Data sheet modifier`
footnote:[
include::special-rules:partial$no-such-ability-in-e40k.adoc[]
]

These units are specially adapted from their original design, to replace their main armament with a more specialised weapon.

---

[NOTE]
.The +{super-heavy weapon}+ placeholder
====
+{super-heavy weapon}+ is a placeholder that we use here to explain a number of related abilities.
You won't see it in the army lists and unit data sheets -- rather, you'll see the name of a specific super-heavy weapon, as in {has-barrage} or {has-macro-weapon}.
====

Where your unit has the {has-super-heavy-weapon} ability, apply these changes relative to its base unit:

* Replace its Firepower value with the corresponding super-heavy weapon.

.The {has-macro-weapon} ability
====
The Leman Russ Vanquisher unit is a Leman Russ base unit with added {has-macro-weapon} ability.

* The base unit has Firepower `3`, whilst the Leman Russ Vanquisher unit has a {macro-weapon} super-heavy weapon instead.
====

.Related information

* xref:special-rules:super-heavy-weapons.adoc[]