= Infiltrators

{unit-ability}

These units are the expert scouts and commandos who gather information, set ambushes, sabotage installations, and so on.

---

Where your unit has the {infiltrators} ability:

* Count it as *in command* while it is within 60 cm of its HQ unit, rather than the usual 30 cm.
footnote:[{e40k-diff}
The original text contains an additional clause: "An _Infiltrators_ unit which is more than 30cm from its HQ unit is still destroyed if it is broken in close combat or a firefight."
This clause alludes to the rules for the Broken condition as it applies to out of command units.
However, to date, we have not been able to find a consistent way to interpret this such that it integrates neatly with the effects of other rules.
So, we include no similar clause here.
If in due course the community finds a way to make sense of this clause with a workable interpretation, then we'll be only too happy to update these rules to add the clause in its new form.
]
////
However, it is still destroyed if it becomes Broken and it is more than 30 cm away from its HQ unit.
////
* You may deploy it up to 30 cm outside of your normal deployment zone for the scenario that you are playing.
Or, if it is not deployed at the start of the battle then, in the turn when it arrives, you may add +30 cm to its first move -- even if that move is to disembark from a transport vehicle or drop pod.

.Related information
* xref:main-rules:hq-units-and-command.adoc[]