= Infiltrators

`Unit ability`

These units are the expert scouts and commandos who gather information, set ambushes, sabotage installations, and so on.

---

Where your unit has the {infiltrators} ability:
footnote:[{e40k-diff}
The original rules contain additional clauses: "_Infiltrators_ units count as being within command distance if they are within 60cm of their detachment HQ ... An _Infiltrators_ unit which is more than 30cm from its HQ unit is still destroyed if it is broken in close combat or a firefight."
We have not been able to determine a straightforward, consistent way to interpret these clauses so that they work neatly alongside the effects of other rules.
So, we include no similar clauses here.
If in due course the community finds a way to make sense of these clauses with a workable interpretation, then we'll be only too happy to update these rules to add the clauses in their new form.
]

////
* Count it as *in command* while it is within 60 cm of its HQ unit, rather than the usual 30 cm.
However, it is still destroyed if it becomes Broken and it is more than 30 cm away from its HQ unit.
////
* You may deploy it up to 30 cm outside of your normal deployment zone for the scenario that you are playing.
Or, if it is not deployed at the start of the battle then, in the turn when it arrives, you may add +30 cm to its first move -- even if its first move is to disembark from transport vehicles or drop pods.

.Related information
* xref:main-rules:hq-units-and-command.adoc[]