= Jump Packs

`Data sheet modifier` `Unit ability`

These units are equipped with jet-powered devices or other technology, wings, or even powerful long legs that allow them to make long jumps across the battlefield.
The resultant speed and mobility usually makes for good assault troops.

---
== Jump Packs added to base units

Where your unit uses the {jump-packs} ability to modify a base unit, apply these changes relative to its base unit:

* Make its first Speed value two times (2x) the *first* Speed value of the base unit.
* Make its second Speed value three times (3x) the *first* Speed value of the base unit.

.{jump-packs} data sheet modifiers
====
The Eldar Swooping Hawks unit is an Aspect Warrior unit with added {jump-packs} ability.

*  While the base unit has a Speed value of `15/30 cm`, that of the Swooping Hawks is `30/45 cm` -- that is, `(15 x 2)/(15 x 3) cm`.
====

include::main-rules:partial$charge-moves-split-speed.adoc[]

== Jump Packs and unique units

Where your unit has the {jump-packs} ability and is a base unit:

* Use the Speed values listed in the unit's data sheet.
+
[NOTE.e40k]
====
Due to the way _Epic Remastered_ displays the final modified Speed values in datasheets, we needed to explain how the {jump-packs} ability works for units that do not have a separate base unit, for example Tau Crisis Suits or Revenant Scout Titans.
====

== Jump Packs and movement

Where your unit has the {jump-packs} ability, apply these rules during the game:

* You may ignore terrain when you move the unit — though you must still take a dangerous terrain test whenever the unit starts a move in dangerous terrain, and whenever it ends a move in dangerous terrain. You may not place the unit on impassable terrain.
+
[NOTE.e40k]
.Dangerous terrain tests
====
In _Epic 40,000_ it wasn't clear whether units with the {jump-packs} ability ignored the standard rules for starting a move in dangerous terrain. After discussion with players, we have applied the standard rules.
====
* When you make a charge move with the unit, you can move it over enemy units that are already in base contact with your other units.
+
[NOTE.e40k]
.Move over contacted enemy units
====
We created this rule as part of efforts to rationalise and improve the rules for Assault moves, after discussion with other players.
====

.Related information
* xref:main-rules:data-sheets-and-characteristics.adoc[]
* xref:main-rules:terrain-effects-on-movement.adoc[]
* xref:main-rules:assault-moves-and-charges.adoc[]
