= Macro-Weapon

These weapons are able to punch through even the thickest armour with ease.

[NOTE]
====
This super-heavy weapon was originally called _Anti-Tank_.
That term tends to mislead players as it implies effectiveness against Vehicle units but perhaps not against other unit types such as Infantry -- whereas the rules below actually make this weapon very effective against all unit types.
We've borrowed the new name from the similar concept in _Epic Armageddon_.
====

---

When you shoot with a {macro-weapon}:

* Specify whether you will target Infantry units or Vehicle units in the target detachment.
Then allocate {macro-weapon} hits as you would for regular Firepower, but allocate only to the nearest units of the type that you specified.
* For each {macro-weapon} shot, roll a D6. If you roll a 4+, the target detachment suffers a hit regardless of Armour values and regardless of cover.

.A classic {macro-weapon} unit
====
The Space Marine Land Raider is both heavily armoured and heavily armed.
It mounts armour-busting lascannons which make short work of thick armour.
====
