= Psychic Beacon

{detachment-ability}
footnote:[{e40k-diff}
The {e40k} version of this ability is exceptionally cheap and powerful -- for only a small cost, it allows all Mycetic Swarm detachments in the army to arrive in turn 1, automatically.
We've revised the ability so that it (a) scales with the number of detachments that have the ability, (b) grants you a re-roll rather than a bypass of the Reserve Detachment Arrival table, and (c) you can use the re-roll for any Tyranid detachment in Reserves, not just Mycetic Swarms.
Note that this also means that the earliest a Mycetic Swarm detachment can arrive from Reserves is turn 2, just like other Reserves.
]

Genestealer Patriarchs emit a strong psychic signal, which guides the parent Hive Fleet to the planet.

---

When you field an army that includes detachments that have the {psychic-beacon} ability:

* For each undestroyed detachment with the {psychic-beacon} ability, you may re-roll one failed Reserves roll per turn.

.Related information
* xref:battles:scenario-special-rules:reserves.adoc[]