= Pulsar (X)

This weapon is unique to the Eldar race, and it demonstrates their mastery of laser weaponry.

The weapon shoots in rapid but powerful bursts, guided by advanced targeting technologies.
As a result, the weapon can destroy multiple targets in a single salvo.

---

When you make a {pulsar-x} shot:

IMPORTANT: A {pulsar-x} shot results in a salvo of {macro-weapon} shots -- but it still only counts as a single super-heavy weapon.
The resultant salvo of {macro-weapon} shots does *not* count as multiple super-heavy weapons for placement of Blast markers, suppression, contribution to firefights, or any other game purpose.

. Determine the number of shots in the salvo, based on the value of `(X)` that we specify -- for example, _`(D3+1)`_ or _`(D6)`_.
footnote:[{e40k-diff}
The 'salvo' value of {pulsar} in {e40k} is D6 only.
This makes it hard to balance the performance and points costs of certain units.
So, we've added _`(X)`_ to support other values too, for more flexible design of units in the army lists.
]
. Resolve that many {macro-weapon} shots against the target detachment.

.Related information
* xref:macro-weapon.adoc[]