= Special abilities

Many units in the game specialise in particular aspects of war, or have unusual abilities.

Rather than have lots of separate profiles and bespoke special rules, we represent these variants and specialisms with rules for various *special abilities*.
Special abilities modify the characteristics in the unit's data sheet, or add rules that change other aspects of how the unit behaves in the game.

If a unit has any special abilities then we state this on the unit's data sheet.
Or in some cases, the army lists offer particular special abilities as upgrades to specific units.
Where a unit has multiple abilities, apply their effects in combination.

IMPORTANT: Where there is a contradiction, special abilities 'override' the normal rules.

.Special abilities
====
As an optional upgrade, an Imperial Guard Command Squad can include a Primaris Psyker.
This upgrades the basic Imperial Guard unit entry to include the {psyker} ability.

In contrast, a Space Marine Librarian is a psyker and is integral to the unit of the same name.
So the {psyker} ability is part of the Space Marine Librarian unit entry.
====

== Types of special ability

Special abilites come in several different forms:

=== Data sheet modifiers

These are the abilities that modify the characteristics in the unit's data sheet, rather than having special effects during a game. For example the {heavy-weapons} ability changes the unit's Range and Firepower.

=== Unit abilities

Thwse abilities can be used during a game, for example a {save} can protect a unit from a hit that it takes, while {jump-packs} give the unit enhanced movement.

=== Detachment abilities

These abilities change the behaviour of an entire detachment during a game, for example {hit-and-run} allows detachments to make a Retreat move after winning a close combat or firefight.

=== Faction abilities

These abilities affect entire armies, for example the Ork army's {ork-initiative} rule that allows them to place Initiative counters back into the mug at the start of the Assault phase.
