= Special abilities

Many forces in the game specialise in particular aspects of war, or have unusual abilities.

Rather than have lots of separate profiles and bespoke special rules, we represent these variants and specialisms with rules for various *special abilities*.
Special abilities modify the characteristics in unit data sheets, or add rules that change other aspects of how a unit, detachment or army behaves in the game.

* If a unit has any special abilities then we state this on the unit's data sheet.
Or in some cases, the army lists offer particular special abilities as upgrades to specific units.
* If a detachment has any special abilities then we state this in the detachment's entry in the army list.
* If an army has any special abilities then we state this in the list for that army.

NOTE: Where there are multiple abilities in effect, apply them in combination.

IMPORTANT: Where there is a contradiction, special abilities 'override' the normal rules.

.Special abilities
====
As an optional upgrade, an Imperial Guard Command Squad can include a Primaris Psyker.
This upgrades the basic Imperial Guard unit entry to include the {psyker} ability.

In contrast, a Space Marine Librarian is a psyker and is integral to the unit of the same name.
So the {psyker} ability is part of the Space Marine Librarian unit entry.
====