= Super Lifta-Droppa

This unusual but powerful weapon is unique to the Orks.
Human tech-priests are at a loss to explain how it works, except to note its effects.

Ork Mekboys use the weapon to focus a traktor beam on the target and then lift the target high above the ground -- or above a juicy secondary target nearby.
Then they drop the first target onto the secondary target...

---

When you shoot with a {super-lifta-droppa}, apply these rules:

. You can target Vehicle and War Engine units, but not Infantry units.
. To hit and lift the target unit, roll a D6: You need to score higher than the initial Damage Capacity value of the target unit.
(Vehicle units have a Damage Capacity value of 1; War Engine units vary, so check their data sheet.)
. For each point by which your score is higher than the target unit's initial Damage Capacity, you can move it up to 1cm in any direction to determine where the {super-lifta-droppa} will drop it.
. The target unit is dropped at the spot you chose, and is automatically destroyed -- if it is a War Engine unit, roll on its Catastrophic Damage table immediately.
. If there is a secondary target at the spot where the target unit is dropped, roll a D6: On a result of 4+ the secondary target takes a hit.

+[TODO: Where it say "automatically destroyed" would this still allow a Vehicle unit with the {save} or {hero} ability to make the roll to avoid destruction? Perhaps not -- but if it should then we'd have to say something about where to place the surviving target if it is dropped on another unit that is not destroyed, or on impassable terrain]+