= Super-heavy weapons

These are fearsome and awe inspiring weapons that equip the most powerful units in the game -- usually war engines, but also some particularly potent specialist units of other types.

Super-heavy weapons may have a variable Firepower value, or no Firepower value at all.
These rules define the effects of super-heavy weapons; see the specific unit data sheets for ranges.

== Shooting with super-heavy weapons

* Where you wish to shoot a unit's super-heavy weapons in the Shooting phase and the unit's Firepower is halved, for example it is on Assault orders or suffering critical damage, you must roll to _lock on_ first.
For each super-heavy weapon being fired, roll a D6. On a roll of 4+ the weapon can fire.

* Where a unit that is equipped with super-heavy weapons is on Overwatch orders: You may re-roll misses when you shoot with these weapons, just as you do with regular weapons.

== Super-heavy weapons in firefights

* Where a unit that is equipped with super-heavy weapons is in a firefight, and a super-heavy weapon doesn't have a basic Firepower value, the super-heavy weapon contributes 1 Firepower to the firefight.
// IJW editing note: To be a closer match to the text used in war engine weapon mounts.

== Super-heavy weapons and placement of Blast markers

When you shoot with a detachment that includes super-heavy weapons, you may get to place two lots of Blast markers:

* For any regular Firepower that your detachment brings to bear on the target detachment, place Blast markers as normal.
* For the super-heavy weapons that your detachment brings to bear on the target detachment, place Blast markers as follows.
+
.Blast marker table
[cols="^,^2"]
|===
^|Number of super-heavy weapons ^| Blast markers placed

^|1 to 3 ^|One, if any hits are scored
^|4 to 8 ^|1
^|9 or more ^|2
|===
+
// IJW editing note: This table and the one in work-out-blast-markers.adoc have been rationalised.
[NOTE]
====
Count the number of super-heavy weapons that you direct at the target detachment.
Do not modify this number because of Assault orders, Blast markers on the shooting detachment, or anything similar.

Super-heavy weapons that add to the detachment's Firepower total, such as {barrage} and {heavy-barrage}, do not count towards the number of super-heavy weapons being fired when inflicting Blast markers.
====

////
+[TODO: Check and consider the wording around this. I seem to remember that there were some inconsistencies or nuances in how Firepower and super-heavy weapons are suppressed by Blast markers. There may be an important difference between how many we "bring to bear" and how many can actually shoot, that also effects Blast marker placement.]+

+[REPLY IJW: Not that I'm aware of, just the overall discussion of inflicting Blast markers based on unmodified firing or effective firing.]+
////

== Super-heavy weapons and suppression by Blast markers

For each Blast marker on a detachment, reduce its Firepower by 1.
If the detachment has more Blast markers than Firepower, or has no Firepower, each remaining Blast marker suppresses one entire super-heavy weapon.

NOTE: The entire super-heavy weapon is suppressed, even if it has multiple shots like a {pulsar}, or adds to a detachment's Firepower, for example {barrage} or {heavy-barrage}.