= Super-heavy weapons
:bm-shw:
:shw-effects:

These are fearsome and awe inspiring weapons that equip the most powerful units in the game -- usually war engines, but also some particularly potent specialist units of other types.

Super-heavy weapons may have a variable Firepower value, or no Firepower value at all.
These rules define the effects of super-heavy weapons; see the specific unit data sheets for ranges.

== Shooting with super-heavy weapons

Half Firepower and 'lock on'::
Where a game effect forces you to halve the Firepower of a detachment or unit, you also suffer a reduction in the effectiveness of its super-heavy weapons.
footnote:[
Common game effects that force you to halve Firepower include Assault orders and some particular critical damage effects for War Engine units.
]
In these situations, you must test to *lock on* with each super-heavy weapon before you can shoot with it.
+
.Lock on
For each super-heavy weapon that you wish to shoot, roll a D6.
On a roll of 4+ the weapon locks on successfully, so you may shoot with it.
Otherwise, you may not shoot with it this time.

Overwatch::
Where a unit that is equipped with super-heavy weapons is on Overwatch orders you may re-roll misses when you shoot with these weapons, just as you do with dice that you get from Firepower.

== Super-heavy weapons and placement of Blast markers

When you shoot with a detachment that includes super-heavy weapons, you may get to place two lots of Blast markers:

* For any regular Firepower that your detachment brings to bear on the target detachment, place Blast markers as normal.
* For the super-heavy weapons that your detachment brings to bear on the target detachment, place Blast markers as follows.

include::main-rules:partial$blast-marker-table.adoc[]

[NOTE]
====
Count the number of super-heavy weapons that you direct at the target detachment.

* Do *not* modify this number because of Assault orders, Blast markers on the shooting detachment, or anything similar.
* Do *not* count super-heavy weapons that add to the detachment's Firepower total, such as {barrage} -- the Firepower component already accounts for any Blast markers that they may add.
====

== Super-heavy weapons and suppression

Normally, suppression means that for each Blast marker on a detachment you must reduce its Firepower total by 1.
However, if the detachment has more Blast markers than Firepower, or has no Firepower, then for each remaining Blast marker you lose the ability to shoot with one super-heavy weapon.
You may choose which super-heavy weapons are suppressed.

NOTE: The entire super-heavy weapon is suppressed, even if it has multiple shots like {pulsar-x}, or adds to a detachment's Firepower like {barrage}.

== Super-heavy weapons in firefights

Where a super-heavy weapon is in a position to contribute to a firefight, it contributes 1 Firepower.

.Super-heavy weapons in firefights
====
The {death-ray} and {heavy-barrage} weapons do not have a basic Firepower value.
Where they are in a position to do so, they each contribute 1 Firepower in a firefight.
====

== Summary of super-heavy weapon effects

include::partial$summary-of-super-heavy-weapon-effects.adoc[]

.Related information
* xref:main-rules:blast-markers.adoc[]
* xref:experimental:experimental-super-heavy-weapons.adoc[]