= Walker

`Data sheet modifier` `Unit ability`

Some vehicles that have legs are able to enter terrain that is problematic for other vehicles.
Thus they can fill niche roles on the battlefield, often in close support of infantry.

[NOTE.e40k]
====
We've brought this ability into the main body of the rules.
In _Epic 40,000_ it was a suggestion in the _Battles Book_, later confirmed in Official Rule Amendments and Errata, _Firepower_, issue 1.
====

---

Where a Vehicle unit has the {walker} ability:

* The unit counts as an Infantry unit for terrain effects on movement.
* The unit has a second Speed value which is two times (2x) the unit's normal Speed value.
// IJW EDITING NOTE: This is awkwardly worded, and I'm not sure we even need it - we can just adjust the Speed values directly. If this bullet is removed, we also need to remove the include below.

include::main-rules:partial$charge-moves-split-speed.adoc[]

NOTE: To be clear, {walker} units do not benefit from the Infantry Armour bonus for cover.

.Related information
* xref:main-rules:terrain-effects-on-movement.adoc[]
* xref:main-rules:assault-moves-and-charges.adoc[]
