= War engines

'War engine' is the term that we use to refer to especially large machines of war.
These include Imperial and Eldar titans, Ork gargants and the super-heavy tanks of various factions.

== War Engine unit abilities

All War Engine units have the {no-retreat} and {unbreakable} abilities.

{blank}[TODO: We could also consider a reminder of this point in both the 'War engines in close combat' and 'War engines in firefights' topics, where the abilities both take effect.]

[NOTE.e40k]
====
These abilities replace the rules that appear under the 'No Retreat, No Surrender' heading in _Epic 40,000_.
====

== Damage Capacity value

War engines can absorb a lot more punishment than normal units.
So, the main difference between the War Engine unit type and other unit types is the Damage Capacity (DC) value.
This indicates how many hits the War Engine unit can take before it is destroyed.

== War Engine unit data sheets

War Engine units are more complex than normal units, so their data sheets are bigger and more detailed.
You can see an example of a War Engine data sheet at xref:war-engine-data-sheets.adoc[].

== War Engine detachments

War Engine units do not mix in detachments with other types of unit.
Rather, we organise and field them in separate detachments of one or more War Engine units.

.War Engine detachments
====
In general, large War Engine units such as 'battle titans' form their own detachment of one unit.

The same can be true of smaller War Engine units such as 'scout titans' and super-heavy tanks -- but it is more usual to group two or more into a single detachment.
====


{blank}[TODO: The Transportation topic says that for transportation units in one detachment to transport another detachment, both detachments must be on the same orders. Given that as standard we don't apply orders to War Engine units, remember to add something to address what should happen when War Engine units act as transportation for another detachment. Perhaps we'll want a specific topic or sub-heading like 'War Engine units as transportation'.]

.Related information
* xref:no-retreat.adoc[]
* xref:unbreakable.adoc[]