= War engines in close combat

== War Engine assault moves and charges

You may move your War Engine units in the Assault phase, and you may make charge moves with them if you wish.
This does not affect the War Engine unit's ability to shoot in the Shooting phase in any way; it always fires at full effect.

War Engine units have a comparatively high Assault value, as you will see on their data sheets.
Lesser units can and must 'gang up' on a War Engine if they are to defeat it in close combat.

You can place as many units in base contact with the War Engine unit as its initial Damage Capacity value.

[NOTE.e40k]
====
In _Epic 40,000_, you could only 'gang up' with half as many units, which meant that smaller War Engine units like Baneblades could only be attacked by two units -- the same as a regular target!
====

== Close combat attacks with a War Engine

War engines can also do a lot more damage in close combat than regular units.

* Roll a number of dice to hit equal to half the current Damage Capacity of the War Engine unit (round up).
* As normal, you can apply hits to any enemy unit in the combat which is in base contact with any of your units.

[NOTE.e40k]
====
In _Epic 40,000_, the rules for close combat attacks with War Engines assumed that you had a single War Engine in combat with the enemy, and that there were no other War Engines or allied detachments in the close combat. This revised version treats all the close combat hits normally, instead of limiting the hits to units in base contact with that specific War Engine.
====

== Close combat attacks against a War Engine

* For each regular unit that you have in base contact with an enemy War Engine, roll a single hit die as normal.
* Ignore power fields and void shields for any hits that you score in close combat -- they damage the War Engine directly.
Roll for critical damage as normal.

== War Engine detachments in close combat

* When a War Engine detachment is in close combat and some of the War Engine units are not in base contact with the enemy, do not add +1 for the units not in base contact.
Instead, add a number equal to half the current Damage Capacity of these War Engines.
This does not prevent the War Engine units from supporting other close combats.

[NOTE.e40k]
====
In _Epic 40,000_, there were rules for War Engines to support *other* close combats, but no rules for supporting a close combat that the War Engine detachment was in. We have adapted the rules for supporting other close combats.
====

.War engines in close combat
====
{blank}[TODO: Need a suitable graphic.]

Your Great Gargant is in close combat with some Space Marine infantry.
It is undamaged, so its current Damage Capacity value is `18`.
This means that you roll nine dice to hit the Space Marine units.

Your opponent may still only roll a number of dice equal to the number of Space Marine units that are in base contact -- four dice, in this case.
====

.Related information
* xref:main-rules:assault-moves-and-charges.adoc[]
* xref:experimental:war-engine-barging.adoc[]