= War engine critical damage

While war engines are huge and able to withstand a lot of damage, they are complex and have weak points.
A lucky or well-placed shot can wreak havoc on critical systems.
This may make the war engine less effective, or accelerate its destruction.

---

With each hit on a War Engine unit there is a chance of *critical damage*.

For each hit that you score on a particular War Engine unit, roll a D6:

[none]
* *1–5*: The hit causes no critical damage.
There is no further effect.
* *6*: The hit causes critical damage.
Make a 2D6 roll on the Critical Damage Table on the War Engine unit's data sheet, to find out what happens.

The Critical Damage Table describes what additional effect the hit has.
// IJW editing note: I've removed the references to locations, as a number of critical results (notable 'Fire' on Gargants and others, and Stunned, Deep Wound etc. on Biotitans) are not associated with a specific location.
Critical damage takes many forms -- inoperable weapons, raging fires, crippled engines, and so on.
The table also states how many extra points to deduct from the War Engine's current Damage Capacity.

Suffice to say that the effects range from minor inconveniences to catastrophic failures.

Some results indicate that the War Engine is Immobilised, and thus unable to move and very easy to hit.
Mark this as appropriate and apply the rules for the Immobilised condition while it remains in effect.

Some results indicate that the effect only lasts 'until repaired'.
You may attempt to repair each repairable critical result on your War Engine at the appropriate step in the Rally phase.

.Related information
* xref:main-rules:orders-and-conditions.adoc#Immobilised[Immobilised]
* xref:main-rules:attempt-repairs.adoc[]