= Assault moves and charges

During the Assault phase you may only move and attack with detachments that you placed on Assault orders in the Movement phase.

== Assault moves

IMPORTANT: For detachments that have Blast markers on them, you must pass a Leadership test before you can move them.

Moves in the Assault phase are subject to all the rules we described for the Movement phase -- except that the Snap-fire rule does *not* apply in the Assault phase.

In addition, when you move each detachment in the Assault phase, move each of its units one after the other. Each unit:

* *Must* move at least 5cm, or into base contact with an enemy within 5 cm. Any movement beyond this is optional.
* *Must* move as directly as possible towards an enemy unit, but that unit does not need to be the nearest enemy, or even in a Detachment that is being assaulted. The unit can detour around Dangerous terrain.
+
[NOTE.e40k]
.Assault moves through Dangerous terrain
====
We have added the option for units to avoid charging through Dangerous terrain.
====
* *Cannot* move away from the closest enemy unit.
** The closest enemy unit is the one that can be reached by the shortest route.
** Any enemy unit that already has a friendly unit in base contact can be ignored.

////
[TODO: I've put the war engine part within comment marks for now, and we can decide if it should be included here or only appear in the WE pages.]
War engines follow the same rules for assault moves, but their own movement rules take priority. War engines can choose not to move in the Assault phase, but will not be able to initiate Close Combats or Firefights if they do not move.
////

== Charge moves

If your unit's Assault move brings it into base contact with an enemy unit, this is referred to as a *charge move*, or a *charge*.

This is the only time that you may move your units into base contact with enemy units.

You can benefit from a special increase to the Speed value of some units *if* this allows them to charge into base contact. If this does not allow them to reach base contact with an enemy unit, you do not get the increase.

* You may double the Speed value of any *Infantry* unit, unless it has a split Speed value.
* Where a unit has a split Speed value such as `20/30 cm`, use the second value.
* For any other unit, use its Speed value in the usual way.
+
[NOTE.e40k]
.Split Speed values
====
We've added split Speed values to make it easier to understand the effects of abilities like {cavalry} and {jump-packs}.
====

TIP: You do not have to move units their full Speed value if you do not want to.
You may simply want to manoeuvre into range for a firefight or to grab an objective, for example.

.Space Marine charge moves
====
A Space Marine detachment of Space Marines, Assault Squads, and Bikes is moving in the Assault phase.

* Each Space Marine unit has a Speed of 10 cm. As they are Infantry units, you can double this value to 20 cm if you charge them into base contact with an enemy unit, otherwise you can only move the unit 10 cm.
* Each Assault Squad unit has a Speed of `20/30 cm`. You can use the second value of 30 cm if you charge them into base contact with an enemy unit, otherwise you can only move the unit 20 cm.
* Each Bike unit has a Speed of 35 cm. As they are Vehicle units you do *not* get an increase to their Speed value if you charge them into base contact with an enemy unit. You can move the unit 35 cm.
====

.Related information
* xref:special-rules:cavalry.adoc[]
* xref:special-rules:jump-packs.adoc[]