= Assault moves and charges

During the Assault phase you may only move and attack with detachments that you placed on Assault orders in the Movement phase.

include::partial$leadership-test-before-move.adoc[]

We call each move that you make with a unit in this phase an *assault move*.
Where you make an assault move that puts your unit in base contact with an enemy unit we call this a *charge move*.
Every charge move is an assault move, but not every assault move is a charge move.

== Assault moves

Moves in the Assault phase are subject to all the rules that we described for the Movement phase -- except that the Snap-fire rule does *not* apply in the Assault phase.
Also, there are some complexities in this Assault phase that mean you need to pay extra attention to the way that you move each individual unit.

When you move a detachment in the Assault phase, move each of its units one after the other.
For each unit:

* You *must* move your unit at least 5 cm -- or into base contact with an enemy unit that is within 5 cm.
Any movement beyond this is optional.
* You *must* move your unit as directly as possible towards an enemy unit.
This does not necessarily mean the *closest* enemy unit, or even one that is in a detachment that you intend to assault.
* You may *not* move your unit away from the enemy unit that it is *closest* to.
 ** You may ignore the closest enemy unit if you already have a friendly unit in base contact with it.
 Then focus on the next closest enemy unit that is not in contact with a friendly unit.

TIP: You do not have to move units more than 5 cm if you do not want to.
You might only want to move units into range for a firefight or to grab an objective, for example.

[NOTE]
.Closest enemy unit
====
The closest enemy unit is the one that your unit could reach by the shortest route.

However, you may detour around dangerous terrain if you wish, to avoid Dangerous terrain tests.
In that case, the closest enemy unit is the one that your unit could reach by the shortest route that does not include dangerous terrain.
====

[NOTE.e40k]
.Assault moves, 'moving past', 'closest' and detours
====
We clarified the requirements to better integrate the 'no moving past' concept.

We added the option for you to avoid dangerous terrain during your assault moves.
====

== Charge moves

If the assault move that you make with a unit puts it into base contact with an enemy unit, then we call this a *charge move*, or a *charge*.

This is the only time that you may move your unit into base contact with an enemy unit.

You can benefit from a special increase to the Speed value of some units, but *only* where you use this increase to reach base contact -- a charge move.

* Where a unit has a split Speed value such as `20/30 cm`, use the second value.
* For any other unit, use its Speed value in the usual way.

include::partial$ganging-up.adoc[]

include::partial$charge-moves-split-speed.adoc[]

.Related information
* xref:terrain-effects-on-movement.adoc#dangerous-terrain-test[Dangerous terrain test]