= Blast markers

Blast markers are a vital part of the game -- many rules use them in some way.

Detachments under your command will often receive Blast markers when the enemy shoots at them, and at some other times too.

== Game effects of Blast markers

The effects of Blast markers will make more sense when you have read the rest of the rules.
But in summary, detachments that have Blast markers on them suffer a range of penalties that include:

* *Shooting*: For each Blast marker on a detachment, reduce its Firepower by 1.
For example, if a detachment with a Firepower of 9 has 3 Blast markers then reduce its Firepower to 6.
* *Movement*: To move a detachment that has Blast markers on it you must first pass a Leadership test.
* *Assaults*: The detachment will be at a disadvantage in close combat and firefights, as as you will find in the relevant topics.

There are some other game effects too, which we explain in the most relevant sections.

== Removal of Blast markers

You may be able to remove Blast markers from these detachments at the appropriate step in the Rally phase.

.Related information
* xref:leadership-test.adoc[]
* xref:roll-to-remove-blast-markers.adoc[]