= Close combat procedure

After a player has made all of their assault moves and charges then, if there are opposing detachments that have units in base-to-base contact with each other, you *must* resolve close combat between them.

IMPORTANT: The first player completes all of their assault moves and charges, and resolves all close combats (and firefights) that they trigger, before the second player gets to do the same.

The player with the Initiative decides the order in which to resolve close combats.
+[TODO: Consider whether instead the order should be decided by the first player while they are resolving their assaults, and then the second player while they resolve their assaults.]+

To resolve a close combat, use the close combat procedure as follows.

[none]
* xref:add-up-assault-values.adoc[]
* xref:work-out-close-combat-bonuses.adoc[]
* xref:roll-to-resolve-close-combat.adoc[]
* xref:work-out-difference-in-combat-scores-and-place-blast-markers.adoc[]
* xref:roll-for-close-combat-hits.adoc[]
* xref:broken-detachments-and-retreats.adoc[]
* xref:multiple-close-combats.adoc[]