= Data sheets and characteristics

== Data sheets

Each unit is defined by a set of characteristics that tell you how fast and how dangerous it is in game terms. These characteristics are detailed in the unit's *data sheet*. You will find data sheets for every unit in the game at xref:armies:armies.adoc[].

.Data sheets
====
Most units have a very simple data sheet that looks something like these:

[options="header"]
|===
|Unit|Type|Speed|Range|Firepower|Assault|Armour|Notes

|Ork Boyz
|INF
|10 cm
|30 cm
|1
|2
|4+
|

|Space Marines
|INF
|10 cm
|30 cm
|1
|3
|5+
|{rapid-fire}, {stubborn}

|Space Marine Rhino
|AV
|30 cm
|-
|0
|0
|5+
|{transport-2}

|===

====

[NOTE]
====
War Engine units have bigger and more complex data sheets, as we explain at xref:special-rules:war-engine-data-sheets.adoc[].
====

== Characteristics

Unit:: The unique name that specifies the kind of unit.

Type:: The unit type of the unit (see xref:units-and-unit-types.adoc[]).
Some rules affect some unit types and not others.

Speed:: The distance that you can move the unit in a single movement action (in centimetres).
It represents a rate at which the unit can move across the battlefield and still be effective when it shoot its weapons.
You can give units orders that allow you to move units farther than this, but their shooting will suffer.

Range:: The maximum effective distance of the unit's weaponry (in centimetres).

Firepower:: A value (usually a number) that represents the unit's effectiveness when it shoots.
A higher number is better.
Some units are armed with super-heavy weapons that make special forms of attack.
These units will usually have a word (such as {barrage} or {macro-weapon}) in place of their Firepower value.

Assault:: This number shows how effective the unit is at close combat.
We use this in the procedure to resolve an assault where units in one detachment charge an enemy detachment and the models are in base-to-base contact.
+
In assaults the Space Marines' genetically enhanced bodies and superior training give them an advantage over Orks, so they have a higher Assault value.

Armour:: This number shows how well protected and/or difficult to damage the unit is.
Basically, you must roll this number or higher on a D6 to score a hit on the unit when you shoot at it.
+
Both Space Marines and Orks are tough but the Space Marines' power armour makes them even tougher, so they have a higher Armour value.

Notes:: If any special rules apply to the unit then we note this here.
You'll find explanations of the effects of these rules at xref:special-rules:special-rules.adoc[].
As you can see, the rules for {rapid-fire} and {stubborn} apply to Space Marines, whereas no special rules apply to Ork Boyz.