= Orders and conditions

Orders and conditions determine most of what you can and can't do with your detachments in a given turn.

We use Order markers to remind us which orders or conditions are in effect with which detachments.

== Orders

As long as a detachment is not subject to any <<Conditions>> then you may give it orders (during the Movement phase, usually).

=== Advance

These are the orders that a detachment operates under by default.
You don't need a marker to indicate these orders, just so long as you can remember which detachments you've already activated under these orders in a given turn.

Movement phase:: You may make a move with units in this detachment.
Shooting phase:: You may shoot with the units in this detachment.
Assault phase:: You may *not* move the units in this detachment.

=== Assault
image::marker-assault-orders.svg[role="left float-gap",width=40,height=40]
These orders allow a detachment to close with the enemy more quickly, at the cost of less effective shooting as they 'shoot from the hip'.
Also, these are the only orders that allow your detachment to move into close combat with the enemy.

Movement phase:: You may make a move with units in this detachment.
Shooting phase:: You may shoot with the units in this detachment -- but you must *halve* their total Firepower.
Assault phase:: You *must* move the units in this detachment, and you may initiate a close combat or firefight.
For the full detail, see xref:assault-moves-and-charges.adoc[].

=== March
image::marker-march-orders.svg[role="left float-gap",width=40,height=40]
These orders allow a detachment to move very quickly -- but it can't shoot, and it will be very vulnerable if it is attacked.

TIP: Be careful! Detachments on March orders are especially vulnerable to enemy attacks.

Movement phase:: You may make a *triple* move with units in this detachment.
That is, make three normal moves in a single sequence.
Shooting phase:: You may *not* shoot with units in this detachment.
+
If your opponent shoots at this detachment then they will use the Marching column on the Firepower table.
Assault phase:: You may *not* move units in this detachment.
+
If the detachment becomes engaged in close combat or a firefight then and you must *halve* the detachment's Assault and Firepower totals.

=== Overwatch
image::marker-overwatch-orders.svg[role="left float-gap",width=40,height=40]
These orders cause a detachment to forgo most of its movement in favour of more accurate shooting.

Movement phase:: You may move units in this detachment up to 5 cm only.
Shooting phase:: You may shoot with units in this detachment -- and you may *re-roll any misses* you roll with the hit dice.
+
+[TODO: Is there any edge case where the detachment might be allowed to shoot outside of the Shooting phase? If so, then might need a note to the effect that the re-roll applies to shooting outside of the Shooting phase as well.]+
Assault phase:: You may *not* move units in this detachment.

=== Special
image::marker-special-orders.svg[role="left float-gap",width=40,height=40]
We use this marker to indicate that special orders are in effect, such as xref:special-rules:flak.adoc[] or xref:special-rules:artillery.adoc#preparatory-bombardment[Preparatory Bombardment].

== Conditions
IMPORTANT: You cannot give a detachment orders while it is subject to a condition.
When a detachment becomes subject to a condition then *any orders that were in effect are no longer valid* -- remove the Order marker (if any) and place the appropriate Condition marker.

=== Broken
image::marker-broken-condition.svg[role="left float-gap",width=40,height=40]
A detachment becomes Broken when it loses a close combat or a firefight.
This means that the detachment is in disarray -- units are in a state of confusion or even panic, seeking cover and unable to accept and respond to orders.

TIP: Be careful!
Broken detachments are especially vulnerable to encirclement and enemy attacks.

Movement phase:: You may make *only* a 20 cm *Retreat* move with units in this detachment (though you don't have to move them at all if you don't want to).
Shooting phase:: You may *not* shoot with units in this detachment.
Assault phase:: You may *not* move units in this detachment.
+
If the detachment becomes engaged in close combat or a firefight then and you must *halve* the detachment's Assault and Firepower totals.

=== Immobilised
image::marker-immobilised-condition.svg[role="left float-gap",width=40,height=40]
This condition applies when a War Engine unit sustains damage that causes it to become immobile.
This might be a temporary condition if it can be repaired, or it might last for the rest of the game.

Movement phase:: You may *not* move this War Engine unit, at all -- not even to turn on the spot.
Shooting phase:: You may shoot with this War Engine unit as normal.
+
If your opponent shoots at this War Engine then they will use the appropriate Immobilised column on the Firepower table.
Assault phase:: You may *not* move this War Engine, at all -- not even to turn on the spot.
Other:: Immobilised War Engine units may not use special orders.
If a war engine becomes Immobilised while it is under special orders then those orders become invalid -- remove the {special-om}.
+
Where the rules state that the War Engine unit is Immobilised "until repaired", you may attempt to repair the War Engine at the appropriate step in the Rally phase.

{blank}[TODO: Clarify: In contrast to other orders and conditions, the Immobilised condition affects a single War Engine unit at a time. What happens as far as orders are concerned for other War Engine units in the same detachment?]