= Terrain effects on movement
:movement:

The terrain of the battlefield will be a big factor in many of your tactical decisions.
You must consider the risks and opportunities that the terrain presents to both your own forces and those of your opponent, at all times.

Terrain affects the movement of ground units in one of three main ways:

* *No effect*: The unit can move through the terrain as normal.
* *Impassable*: The unit cannot move through the terrain at all, under any circumstances.
* *Dangerous*: The unit can attempt to enter the terrain but it might get stuck, or even suffer damage.
When you wish to move a unit through dangerous terrain you must take a <<Dangerous terrain test>> for that unit.

The effects often differ between *unit types*.

include::partial$terrain-effects-table.adoc[]

[[dangerous-terrain-test]]
== Dangerous terrain test

When you wish to move a unit into dangerous terrain, or when you wish to move a unit that is already in dangerous terrain, roll a D6:

* On a result of 1: You may not move the unit any farther — leave it at the edge of the dangerous terrain.
Or, where the unit is already in dangerous terrain, you may not move it.
Then roll a D6 again: If you roll another 1 then the unit takes a hit.
* On any other result: You may move the unit as normal.

include::partial$effect-of-hits.adoc[]

NOTE: Hits from dangerous terrain do *not* cause critical damage on War Engine units.

== [[roads]]Movement on roads

Where you will move a unit such that its entire move will take place on a road -- in any phase -- add 5 cm to its Speed value for that move. If the unit has a split Speed value, add 5 cm to its first Speed value and 10 cm to its second Speed value.

.Movement on roads
====
An Ork Boyz Infantry unit is on March orders.
Ork Boyz have a Speed value of `10/20 cm`.

The player will make the first two moves entirely on roads, and the third move will include some open ground.

So, the player could move the unit up to a maximum of 40 cm.
That is, up to 30 cm for the first two moves that are on roads ((`10 cm` first Speed value + 5 cm road bonus) x2), plus up to 10 cm for the third move that is not entirely on roads.
====

.Assault moves on roads
====
You have an Ork Boyz Infantry unit that is on Assault orders.
Ork Boyz have a Speed value of `10/20 cm`.

You intend to make an entirely road-based assault move.
So, you can make either:

* A normal assault move of between 5 and 15 cm (`10 cm` first Speed value + 5 cm road bonus).
* A charge move of up to 30 cm to reach base contact with an enemy unit (`20 cm` second Speed value + 10 cm road bonus).
====

.Related information
* xref:terrain-effects-on-shooting.adoc[]
