= Terrain effects on movement
:movement:

The terrain of the battlefield will be a big factor in many of your tactical decisions.
You must consider the risks and opportunities that the terrain presents to both your own forces and those of your opponent, at all times.

Terrain affects the movement of ground units in one of three main ways:

* *No effect*: The unit can move through the terrain as normal.
* *Impassable*: The unit cannot move through the terrain at all, under any circumstances.
* *Dangerous*: The unit can attempt to enter the terrain but it might get stuck, or even suffer damage.
When you wish to move a unit through dangerous terrain you must take a <<Dangerous terrain test>> for that unit.

The effects often differ between *unit types*.

include::partial$terrain-effects-table.adoc[]

[[dangerous-terrain-test]]
== Dangerous terrain test

When you wish to move a unit into dangerous terrain, or when you wish to move a unit that is already in dangerous terrain, roll a D6: On a roll of 1, halt the unit at the edge of the terrain.
If the unit is halted in this way, roll the D6 again: If you roll another 1 then the unit takes a hit.

include::partial$effect-of-hits.adoc[]

NOTE: Hits from dangerous terrain do *not* cause critical damage on War Engine units.

== [[roads]]Movement on roads

Where you will move a unit such that its entire move will take place on a road -- in any phase -- add 5 cm to its Speed value for that move.
Apply this bonus to the unit's base Speed value, before modification.

.Movement on roads
====
An Ork Boyz Infantry unit is on March orders.
Ork Boyz have a Speed value of 10 cm.

The player will make the first two moves entirely on roads, and the third move will include some open ground.

So, the player could move the unit up to a maximum of 40 cm.
That is, up to 30 cm for the first two moves that are on roads ((10 cm Speed value + 5 cm road bonus) x2), plus up to 10 cm for the third move that is over at least some open ground.
====

.Related information
* xref:terrain-effects-on-shooting.adoc[]