= The Start phase

The Start phase comprises preparatory steps which aren't always necessary -- the need for them is determined by what rules you use in your game, and what special orders you want to use for the new turn.

== 1. Roll for Reserves

If you are playing a scenario that uses the Reserves rules, then apply those rules now.

== 2. Declare flyer missions and special orders

There are some things that you must declare now if you want to use them:

* Flyer missions.
* Some types of special orders, such as Flak, Preparatory Bombardment and Dodge.

Start with the player whose army has the lower Strategy Rating, and then alternate to declare until you both run out of things to declare.
Take Leadership tests in the normal way, where the rules require it for you to successfully set the orders you declare.

== 3. Prepare the Initiative counters

Gather the five Initiative counters and place them in the mug (or other receptacle).

*Related information*

* xref:battles:reserves.adoc[]
* xref:special-rules:aircraft.adoc[]
