= The Start phase

The Start phase comprises preparatory steps, some of which you won't need if certain special rules aren't active.

[NOTE.e40k]
====
We made this new phase to clarify the order of events for things that need to happen at or close to the start of the turn.
_Epic 40,000_ is sometimes unclear about interactions at "the start of the turn" and "the start of the Movement phase, before initiative is drawn".
====

== 1. Roll for Reserves

If you are playing a scenario that uses the Reserves rules, then apply those rules now.

== 2. Declare flyer missions and special orders

There are some things that you must declare now if you want to use them:

* Flyer missions.
* Some types of special orders, such as Flak, Preparatory Bombardment and Dodge.

Start with the player whose army has the lower Strategy Rating, and then alternate to declare until you both run out of things to declare.
Take Leadership tests in the normal way, where the rules require it for you to successfully set the orders you declare.

== 3. Prepare the Initiative counters

Gather the five Initiative counters and place them in the mug (or other receptacle).

.Related information
* xref:battles:reserves.adoc[]
* xref:special-rules:flyers.adoc[]