= Transport

On some unit data sheets you'll see that the unit has the {transport} special ability.
We explain special abilities in more detail at xref:special-rules:transport-x.adoc[], but transport is a vital aspect of the Movement phase so we'll discuss it here too.

Units that have the {transport} special ability can carry other units across the battlefield.

* To embark or disembark other units (or cargo) costs the {transport} unit 5cm of its movement.
* An embarking or disembarking unit must also pay 5cm of its movement.
* You may embark and disembark units in the same turn, the same phase or even in the same move -- so long as all of the involved units have enough movement.
* You may perform no other actions with units that are embarked -- so, you cannot shoot with them, for example.
Obviously, once you disembark them then the normal rules apply again.

== Destruction of {transport} units

If a {transport} unit is destroyed then, just before you remove the unit as a casualty, roll a D6 for each embarked unit:

* *1–3*: The embarked unit suffers a hit.
* *4–6*: The embarked unit survives -- place it in contact with the destroyed {transport} unit.

Then remove the {transport} unit as normal.

== Hitch

On some unit data sheets you'll see that the unit has the {hitch} special ability. Infantry units can 'hitch a lift' on {hitch} units -- they simply grab onto the outside of the vehicle and hang on for a crazy ride over the battlefield.

* To embark and disembark other units does not cost the {hitch} unit any of its movement.
* An embarking or disembarking unit must pay all of its movement.
* Any embarked unit *must* disembark at the end of the {hitch} unit's move, or at the end of its last move during a March order.
* A unit can only hitch a lift once per phase.


.Related information
* xref:special-rules:transport-x.adoc[]
* xref:special-rules:hitch-x.adoc[]
