= Transportation

On some unit data sheets you'll see that the unit has one of two special abilities that relate to transportation: {transport-x} or {hitch-x}.

These abilities indicate units that can carry -- transport -- other units across the battlefield.
These abilities have some features in common, but also differ in some important ways.

To refer to the actions that we take with units that we transport, we use the terms *embark* and *disembark*.
To refer to the units that we transport, we sometimes use the term *cargo*.

[NOTE.e40k]
.Transportation
====
The Transport rules in _Epic 40,000_ leave a lot of room for interpretation, and they aren't entirely clear on some of the commonalities and differences between _Transport_ and _Hitch_.
Nor do they account well for disparities that stem from the range of different base sizes that Epic enthusiasts use for their units these days.

To minimise these problems, we've integrated the {transport-x} and {hitch-x} abilities with some new conditions.
====

NOTE: To be clear, a transportation unit does not gain the abilities of any embarked units.

== Transportation by {transport-x} units

:by-transport-x:
include::partial$transportation-by-transport-units.adoc[]

:!by-transport-x:

== Transportation by {hitch-x} units

:by-hitch-x:
include::partial$transportation-by-transport-units.adoc[]

:!by-hitch-x:

== Destruction of transportation units

If a transportation unit is destroyed then any cargo unit that is embarked at the time may also suffer a hit.
Before you remove the destroyed transport unit, roll a D6 for each embarked unit: On a result of 1, 2 or 3, it suffers a hit.
If the unit survives, place it completely within 5 cm of the destroyed transportation unit.

Then remove the transportation unit as normal.

[NOTE.e40k]
.Destruction of transportation units
====
We make it clear that embarked units are subject to the same risk when their transportation unit is destroyed, regardless of which transportation ability is in effect.
====

== Transportation of units from another detachment

Where transportation units from one detachment carry units from another detachment, both detachments must be on the same orders.

[NOTE.e40k]
.Transportation of other detachments
====
We make this restriction to avoid oddities that arise where transportation units and cargo units are under different orders.
====

.Related information
* xref:special-rules:transport-x.adoc[]
* xref:special-rules:hitch-x.adoc[]