= Transportation

On some unit data sheets you'll see that the unit has one of two special abilities that relate to transportation: {transport-x} or {hitch-x}.

These abilities indicate units that can carry -- transport -- other units across the battlefield.
These abilities have some features in common, but also differ in some important ways.

== Embark and disembark
To describe the actions that relate to the units that you transport we use the terms *embark* and *disembark*.
Where we refer to these actions, keep these additional points in mind:

Embark:: 
You may embark a unit only when it is completely within 5 cm of the transportation unit.
Disembark::
When you disembark a unit, place it completely within 5 cm of the transportation unit.

[NOTE.e40k]
.Embark and disembark
====
The transportation rules in _Epic 40,000_ leave a lot of room for interpretation, and they aren't entirely clear on some of the commonalities and differences between _Transport_ and _Hitch_.
Nor do they account well for disparities that stem from the range of different base sizes that Epic enthusiasts use for their units these days.

We've changed the conditions or embarkation and disembarkation and integrated them with the {transport-x} and {hitch-x} abilities to minimise these problems.
====

NOTE: To be clear, a transportation unit does not gain the abilities of any embarked units.
// TODO: However, some abilities, or parts of abilities, can still operate from within a transportation unit. See comment further down, in relation to 'no other actions with embarked units'.

== Transportation by {transport-x} units

To embark or disembark one or more units:

* You must sacrifice 5 cm from the movement of the {transport-x} unit.
* You must sacrifice 5 cm from the movement of the unit that you embark or disembark.
* You may embark and disembark units in the same turn, the same phase or even in the same move -- so long as all of the involved units have enough movement.

You may perform no other actions with embarked units -- so, you cannot shoot with them, for example.
Obviously, once you disembark them then the normal rules apply again.
// TODO: I think we might need to refine this because 'action' might be ambiguous -- for example, shouldn't the 'stubborn' part of the Supreme Commander ability still be allowed even while the unit is inside transportation, while the 're-roll Assault resolution die' part would not?

TIP: When you disembark a unit from a {transport-x} unit, you sacrifice 5 cm of its movement and place it completely within 5 cm of the {transport-x} unit.
In practice, this means that you can simply measure its movement from the {transport-x} unit.

== Transportation by {hitch-x} units

To use the {hitch-x} ability to transport one or more Infantry units:

* You do *not* need to sacrifice any of the movement of the {hitch-x} unit.
* You must sacrifice *all* of the movement of the Infantry unit.
* You must embark *and* disembark your Infantry units in the same move, or the same series of moves if the {hitch-x} unit is on March orders.
Embark the units at any point during your move of the {hitch-x} unit, and disembark at another point in same move, or series of moves.
* You may only embark your Infantry unit onto a {hitch-x} unit once per phase -- you may not hitch a lift multiple times with the same Infantry unit.

== Destruction of transportation units

If a transportation unit is destroyed while other units are embarked then, before you remove the unit as a casualty, roll a D6 for each embarked unit: On a result of 1, 2 or 3, the embarked unit suffers a hit.
If the embarked unit survives, place it completely within 5 cm of the destroyed transportation unit.

Then remove the transportation unit as normal.

[NOTE.e40k]
.Destruction of transportation units
====
We make it clear that embarked units are subject to the same risk when their transportation unit is destroyed, regardless of which transportation ability is in effect.
====

== Transportation of units from another detachment

Where transportation units from one detachment carry units from another detachment, both detachments must be on the same orders.
// IJW editing note - the war engine orders page will need a note saying how this works if you're *not* using war engine orders.
// TODO: I wonder if we should thrash this detail out in the Experimental section? I mean, the original war engine orders rules were an afterthought and by no means universally accepted. Thus, I suggest that until such time as we nail down an alternative we should default to the original 'no orders' -- in which case this tract won't make sense here anyway.

[NOTE.e40k]
.Transportation of other detachments
====
We make this restriction to avoid oddities that arise where transportation units and embarked units are under different orders.
====

.Related information
* xref:special-rules:transport-x.adoc[]
* xref:special-rules:hitch-x.adoc[]