= Units and unit types

Colossal war engines loom over the battlefield and unleash untold devastation upon their targets.
Vehicles probe and break through enemy lines, or prevent enemy attempts to do the same.
Aircraft fight for dominance of the sky and bomb enemy positions.
Infantry rush from cover to cover and fight desperate hand-to-hand combats to secure positions that other forces can't reach or can't hold.

All these forces must work together to secure victory for their side.

== Units
The playing pieces that we use to play {project-name} represent the many and varied forces that are at war on battlefields of the 41^st^ millennium.

In game terms, each individual playing piece represents a single independent element of these forces, known as a *unit*.
Each unit is also of a particular named kind, such as Ork Boyz or Land Raider.
Each kind has a unique set of characteristics that define its capabilities on the battlefield, which we explain at xref:data-sheets-and-characteristics.adoc[].

== Unit types [[unit-types]]
Units vary widely in their specific capabilities, but all belong to a broad *unit type*, as follows:

=== Infantry (`INF`)
Essentially, personnel that are able to deploy and act 'on foot'.

This includes infantry like Space Marine troopers and Ork Boyz, and field artillery such as the Eldar Support Platform and Ork Pulsa Rokkit.

We typically represent Infantry units as follows:

* 'Normal' infantry: Up to five infantry models affixed to a single base.
This is also known as a 'stand'.
* Field artillery: One artillery piece model affixed to a single base, along with some infantry models to represent the crew.

TIP: Wargamers also often refer to the physical representation of an infantry unit as a 'base' or 'stand' of infantry.

{blank}[TODO: Consider whether to include some text similar to that at link:https://thehobby.zone/resources/ea-rules-revamp/Content/CoreRules/Basics/StandsInfantryUnits.htm[^] (external URL) -- but a bit more inclusive.]

=== Vehicle (`VEH`)
Vehicles, some large beasts, and mounted infantry.

Vehicle examples include tanks such as the Leman Russ and Land Raider, armoured troop carriers such as the Rhino, and other machines such as Dreadnoughts.
Mounted infantry examples include Space Marine Bike units and Ork Boarboyz units.
Large beasts include the Ork Squiggoth and the Tyranid Carnifex.

We typically represent Vehicle units as follows:

* 'Normal' vehicle: A single vehicle model.
footnote:[
Some players like to affix their vehicle models to bases, but this is not necessary and makes little difference in game terms.
Do as you prefer.
]
* Large beast: A single beast model, usually affixed to a base for stability.
* Mounted infantry: Two or three mounted infantry models affixed to a single base.

=== War Engine (`WE`)
Very large machines of war.

Examples include the super-heavy tanks and Titans of various factions, Gargants (which are the Ork equivalent of Titans) and some giant bio-constructs such as the Tyranid Dominatrix.

These units dwarf the units of other unit types and can absorb a lot more damage before they are destroyed.
Best of all, these behemoths usually have multiple giant weapon systems that can rain destruction upon your enemies!

We represent each War Engine unit with a single model.
footnote:[
Some players like to affix their war engine models to bases, but this is not necessary and makes little difference in game terms.
That said, where a war engine model has legs, it is usual to affix it to a base -- both for stability and for clarity of measurements and other interactions during the game.
]

=== Flyer (`FLY`)
Aircraft, and even some creatures that can fly within a planet's atmosphere.
They are very fast relative to ground units.
Examples include the Ork Fighta-Bommer, Space Marine Thunderhawk Gunship and Tyranid Harridan.

We usually represent each Flyer unit with a single model on a 'flying stand' -- that is, the model sits on top of a vertical rod that is affixed to a base, to raise the model above the height of other units on the tabletop.

[NOTE]
====
Note that 'skimmer' units such as the Space Marine Land Speeder and Eldar Falcon grav-tank are not aircraft, and do not count as Flyer units.
Rather, these units have some unique capabilities that we represent with the {skimmer} special ability.
Otherwise, they behave just like other 'ground units'.
====