= S1. Add up shooting Firepower

. Measure the range from units in your shooting detachment to the target detachment.
. For every one of your shooting units that has a <<Line of fire>> and is within range of at least one target unit: Add their Firepower values together to create a total.
////
. For each Blast marker on the detachment, reduce its Firepower by 1.
For example, if a detachment with a Firepower of 9 has 3 Blast markers then reduce its Firepower to 6.

// TODO: Check this -- IIRC there is a rule somewhere that seems to imply that the unmodified Firepower is used to place Blast markers in the next step.
////

.Adding up shooting Firepower
====
+[TODO: Need new image and example text.]+
////
A Space Marine detachment consisting of 4 Space Marine units, 2 Devastator Space Marine units and 2 Predator tanks fires at an Ork detachment.
Their Firepower is worked out as follows.

Three of the Space Marine units are in range (3 Firepower). Both Devastator units are in range (4 Firepower).
Both Predators are in range, though one of them is behind a wood and so has no line of fire to the Orks -- only one Predator adds its Firepower to the total (2 Firepower).
This gives a total of 3+4+2=9 Firepower.
////
====

== Line of fire

To shoot, units must have a 'line of fire' to at least one unit in the target detachment.

* Line of fire is blocked by terrain features such as buildings, hills, woods and so on.
It is also blocked by war engine units -- but not by other units.
* Buildings and woods don't block the line of fire to or from units that are *in* the terrain itself.
* Units which are higher up can see over and be seen over any terrain that is lower than they are.

Terrain conventions and line of fire are both discussed in more detail in the Battles Book [House rules, frequently asked questions and other nonsense].
+[TODO: Rationalise content and fix this xref.]+

== Fire arc

Vehicles and infantry can shoot in any direction.
You may turn the miniatures to face their targets if you wish, but it makes no difference as far as the rules are concerned.

War engines are different -- see xref:special-rules:shooting-with-war-engines.adoc[].

== Splitting fire

Each unit may only shoot once in the Shooting phase.
But, when you choose a detachment to shoot with, you may split its shooting between multiple target detachments.
Resolve the shooting against each target detachment separately, in whatever order you like.

.Splitting fire among multiple target detachments
====
+[TODO: Need new image and example text.]+

////
A Space Marine detachment is faced by two Ork detachments.
The Space Marine player elects to split his fire between the two enemy detachments.

The Space Marines have a total Firepower of 21.
They direct 14 of this towards one detachment and 7 against the other.
Each attack is worked out separately, hits being allocated against units in the specific detachments as usual.
////
====