= S6. Allocate hits

Allocate your successful hit dice against eligible units in the target detachment.

* Allocate one die at a time, starting with the nearest available target unit, then the next closest, and so on.
You may choose which individual hit die you allocate in each case, but you must allocate in this order for all hit dice.

* You must allocate every successful hit die to a target unit, whether or not it can actually affect that unit.
+
So for example: You've allocated most of your hit dice and your last remaining hit dice all have a score of 4.
The next-nearest target unit has Armour 6.
You must still allocate one of the 4's against this unit -- even though it will be wasted (the shot bounces off harmlessly).
You may *not* ignore a nearer unit so as to allocate a hit to a unit that is farther away instead.

* You may only allocate one hit to each eligible unit in a target detachment until all eligible units have been allocated a hit already.
Then you may allocate each unit a second hit starting with the closest. If all the units have taken two hits you may allocate a third, and so on.

[IMPORTANT]
====
* You may not allocate hits to target units that are in cover unless unless you used the *Vehicles or Infantry in Cover* column on the Firepower table.

* You may only allocate hits against units in the target detachment that are in range and in the line of fire of at least one of your shooting units -- if a target can't shot at in the first place then it can't be hit either!
====

.Allocating hits step (i)
====
+[TODO: Need new example image and text.]+

A detachment of Space Marines is firing at a mixed detachment of Orks and Battlewagons. The Space Marines have a Firepower of 9.
Some of the target detachment are in cover, some of them are in the open.

The Space Marine player decides to ignore the Orks in cover to fire at those in the open.
Consulting the Firepower table he sees that firing at infantry and vehicles in the open gives him five dice.
He scores a 5, 4, 4, 3 and 2.
The lowest Armour value in the target detachment is 4+ for the Ork Boyz.
The 2 and the 3 are discarded as misses.
====

.Allocating hits step (ii)
====
+[TODO: Need new example image and text.]+

. The closest unit to the Space Marines is a Boyz unit, the Space Marine player allocates one of the 4's to it and it is destroyed.
. The second closest unit is a Boyz unit in cover.
As he did not fire using the cover column or the Firepower table this unit cannot be hit and is ignored.
. The next closest unit is a Battlewagon.
The 5 is allocated to it and it is destroyed.
. The next closest unit is another Boyz unit in cover, again this is ignored.
The next closest unit is another Battlewagon behind a wood.
No Space Marine unit in the firing detachment has a line of sight to it, and therefore it cannot be hit.
. The next closest unit is a third Battlewagon.
The 4 must be allocated to this, and as a Battlewagon is Armour 5+ the shot bounces off harmlessly.

Firepower 9 also places one Blast marker on the Ork detachment (as noted at xref:work-out-blast-markers.adoc[]).
====