= Leadership test

== When to take a Leadership test

* When your detachment has one or more Blast markers on it, you must pass a Leadership test before you can move it under orders in any phase or set Overwatch orders.
// What happens if you try to set Overwatch orders and fail? Fall back onto standard orders? What about special orders?
+
NOTE: A Broken detachment is not under orders and no Leadership test is required to make a Retreat move (see xref:broken-detachments.adoc[]).

* If your detachment is Broken then you can try to pass a Leadership test to rally it near the end of the turn, during the appropriate step of the Rally phase.
// TODO: Check -- should the +! bonus for 15 units or more apply in the Rally phase?

== How to take a Leadership test

To take a Leadership test, roll a D6: If you score higher than the number of Blast markers that are on the detachment then you pass -- otherwise you fail.

* If you detachment currently has 15 or more units in it, add +1 to the score.
* A roll of a natural 6 is always a pass, no matter how many Blast markers are on the detachment.