= Multiple close combats

Several close combats may need to be fought in the same Assault phase if a number of different detachments enter close combat with enemy detachments.
In an ideal world these would each only involve one detachment per side, but things being what they are it's inevitable that units from several detachments will end up fighting each other.
Where two or more detachments are in contact with one or more enemy detachments, resolve the fight as a single large combat.

.Multiple close combats
====
+[New image and text required.]+
// New image and text required.

Two Ork detachments charge into a Space Marine detachment.
Both Ork detachments and the Space Marines have models in base contact with the enemy so any units not in contact but within 15cm can add supporting fire (see Close Combat Procedure [The Assault phase]).

The second unengaged Space Marine detachment has no models involved directly in the assault and so may not lend any support.

The Assault values of both Ork detachments are added together to find the Orks' total.
If they lose both detachments will have the same number of Blast markers placed on them, will both be broken and will have to retreat.
====
