= The Shooting phase

There are two parts to the Shooting phase: first, both sides shoot with vehicles and infantry; second, both sides shoot with war engines.
You must determine the initiative in each part.

In each part, the player with the Initiative chooses a detachment and shoots with them first -- and then the players alternate.

You may pass on an opportunity to shoot, if you'd like to hold back and shoot later in the current part of the Shooting phase instead.
*However*, if your opponent *also* passes immediately after you pass then this part of the Shooting phase ends immediately!
// Could a player pass in the first part and then shoot in the second part instead?

To resolve shooting, use the shooting procedure as follows.

== Shooting procedure

[none]
* xref:add-up-shooting-firepower.adoc[]
* xref:work-out-blast-markers.adoc[]
* xref:work-out-how-many-hit-dice-to-roll.adoc[]
* xref:find-out-the-targets-lowest-armour-value.adoc[]
* xref:roll-for-shooting-hits.adoc[]
* xref:discard-misses.adoc[]
* xref:allocate-hits.adoc[]
* xref:remove-casualties.adoc[]