= The Initiative

In each phase of the turn, one player or the other will have the Initiative.
This is important because it determines which player will act first in the events of that phase -- which can be a crucial advantage.

The player with the Initiative goes first, or gets to choose who goes first, depending on the phase.

.Determine the Initiative
To determine who has the Initiative we draw an Initiative counter from a mug (or another receptacle, such as a small bag):

. At the start of the turn, place five Initiative counters in the mug: three for the player whose army has the higher Strategy Rating, and two for the player whose army has the lower Strategy Rating.footnote:tie-break[If both armies have the same Strategy Rating then at the start of the game roll-off to decide which army gets the advantage for this game.]

. Where the Turn Sequence instructs you to "Determine the Initiative", one player must draw a counter from the mug. The player whose counter is drawn has the Initiative.

. That player has the Initiative until the next "Determine the Initiative" step in the turn -- at which point they may get the Initiative again, or the opposing player may get it, depending upon what counter is drawn.
+
*Do not put counters back into the mug until the end of the turn, in readiness for the next turn.*