= Engineers

These units perform special technical duties to support the rest of the army, often while under fire.
They clear routes through minefields, erect defences in the field, and use explosives to demolish enemy fortifications.

---

Apply these rules to units with the {engineers} ability:

== Mine clearance

[TODO: The original text is very unclear about when and how the {engineers} units can make an Assault move into a minefield, and how they should work meaningfully with the Hidden Setup rules for booby traps and minefields.

* What is a 'mine counter'?
A minefield terrain piece, or a hidden setup marker, or something else?
* Presumably you must make the mentioned Assault move towards the minefield or hidden setup marker in the preceding Assault phase, not in the Rally phase.
* How should that Assault move work?
** Should we act such that the whole detachment treats minefields and/or hidden setup markers as enemies that they can move towards for the purpose of the Assault move?
** Can the detachment or at least the {engineers} units make a charge move to reach and enter the minefield or trigger the hidden setup reveal?
** On a hidden setup reveal, what's the point if the opponent chooses booby traps, which are 'one and done', nothing further for {engineers} units to do?
** Should it be a requirement that the {engineers} units don't contribute to a close combat or firefight in order to focus so that we can remove 'mine counters' in the Rally phase?
]

== Field defences
[TODO: Again, there should be more clarity about orders and the rest of the detachment while {engineers} units must remain stationary so that we can place a fortification or razorwire in the Rally phase.
]

== Demolitions
[TODO: Again, how should the Assault move against fortifications work?
]

*Related information*

* _Epic 40,000 Compendium_: link:https://thehobby.zone/resources/e40k-compendium/Content/SpecialRules/SpecialistsAndSpecialAbilities/Engineers.htm[Engineers^] (external URL)