= Portal

`Unit ability`
footnote:[
include::special-rules:partial$no-such-ability-in-e40k.adoc[]
]

Some races employ technologies that allow them to open trans-dimensional portals on the battlefield.
This can be an effective method to deploy reserve forces at the optimum time and place.

Well-known examples include Necron portals and Eldar Webway portals.

---

[NOTE]
====
This ability lets you keep detachments outside of the play area at the start of the game, similar to Reserves.
You can then deploy them later in the game.
When they arrive, you disembark them into the play area through a unit -- or objective -- that has this ability.
====

== Data sheet variations of {portal}

Where we include {portal} on a unit data sheet -- or for an objective -- we also include some further information, as attributes in brackets.
For example, like this: `{portal} _(INF, 4+, {walker}, Auto)_`.

Mostly, these attributes indicate what other friendly units can actually pass through the portal -- that is, which kinds of unit you can embark/disembark through that portal during the game.

* `_(INF)_`: Infantry units.
* `_(4+)_`: Vehicle units that have an Armour value of `4+` or lower.
* `_({walker})_`: Vehicle units that have the {walker} ability, regardless of their Armour value.

We also indicate how the portal affects the arrival of detachments that use it:

* `_(Auto)_` means that detachments in Portal Reserves do *not* follow the standard rules for Reserves.
Instead, from turn two onwards, you must *must* disembark them from a {portal} unit/objective in the Movement phase unless there are not enough portals available, or none of the available portals can disembark all of the units in the detachment.
* `_(Roll)_` means that detachments in Portal Reserves follow the standard rules for Reserves.
When a detachment arrives from Portal Reserves, you *must* disembark it from a {portal} unit/objective, if possible.

== Game effects of {portal}

Where your army includes any units or objectives that have the {portal} ability:

* Regardless of the scenario, you may keep any detachments that contain units that can use a portal out of the play area, as <<Portal Reserves>>.

Where your unit or objective has the {portal} ability:

* When you wish to move a detachment into or out of a portal, you may choose only Advance or Assault orders.
* When you wish to move a detachment into or out of a portal, use the normal xref:main-rules:transportation.adoc[] rules to embark and disembark the units.
footnote:[
When you disembark units from an *objective* that has the {portal} ability, you obviously cannot pay 5 cm of its movement like you would with a mobile transport unit.
In this case, just deduct 5 cm from the movement of each unit that you disembark, as usual, and ignore the deduction that would normally apply to the transport unit.
]
* You may use each individual portal only *once per turn*, to embark or disembark a single detachment.
* You cannot use portals to transfer detachments *out* of the play area during the game.
However, in the Movement phase only, you may move a detachment that is already in the play area into an available portal -- but then you *must* immediately disembark the detachment from a different available portal elsewhere in the play area.

== Portal Reserves

Apply these rules to each detachment that you have outside of the play area as Portal Reserves.

When the detachment should arrive, you *must* put it into play if possible -- but you may only put it into play through a suitable, available portal.

* If there is no portal available when you need it, then you must leave the detachment in Portal Reserves this turn -- it does not arrive yet after all.
You must roll again next turn.
* If none of the available portals can disembark all of the units in the detachment, then you may choose, either:
** Leave the detachment in Portal Reserves this turn -- it does not arrive yet after all.
You must roll again next turn.
** Disembark as much of the detachment as you can.
The units that cannot disembark are immediately destroyed.
Place a Blast marker on the detachment.

IMPORTANT: If the detachment does not arrive and enter play before all {portal} units/objectives in your army are destroyed or the game ends, then the detachment counts as destroyed for the purposes of this game.
footnote:[
If you're playing a scenario that uses the Army Morale rules, deduct the detachment's Morale Value from your morale total at the end of the Rally phase, as normal for a destroyed detachment.
]
footnote:[
We consider the detachment to be 'destroyed' for the sake of the battle, but not for the war.
That is, treat the detachment as destroyed for all rules purposes in the current game -- but not for future games, if you're playing a campaign.
]

== Example of {portal} in action

.Necron Portals
====
You have a Necron army which includes, among other things, two different {portal} units:

* A Monolith `WE` unit -- which has `{portal} _(INF, 4+, Auto)_`.
* A Warbarque `WE` unit -- which has `{portal} _(INF, {walker}, 4+, Auto)_`.

Your army also includes two detachments that you decide to keep outside of the play area, as Portal Reserves:

* Detachment A, which contains some Necron Warriors (`INF`), Lokhust Destroyers (`INF`), and Tomb Blades (`VEH` with Armour `4+`).
* Detachment B, which contains some Necron Immortals (`INF`), Canoptek Spyders (`VEH` with `{walker}`), and a C'Tan Shard (`VEH` with `{walker}`).

You can use detachments A and B with the {portal} units as follows:

* You can keep detachment A outside of the play area as Portal Reserves at the start of the game.
Later, you can use either {portal} unit to disembark it later.
* You can keep detachment B outside of the play area as Portal Reserves at the start of the game.
Later, you can either:
** Use the Warbarque unit's portal to disembark it later.
** Use the Monolith unit's smaller portal to disembark it later -- but in this case, the Canoptek Spyders and the C'Tan Shard are *destroyed* and you must place a Blast marker on the Immortal units that form what's left of the detachment.
====

.Related information
* xref:battles:scenario-special-rules:reserves.adoc[]
* xref:main-rules:transportation.adoc[]