= War engine barging

IMPORTANT: This rule is for playtesting purposes and is not finished content.

An experimental option to improve the rules for when you make a charge move with a War Engine unit.

****
.The problem
Often, when you make a charge move with your War Engine unit, you'd like to move it into base contact with multiple enemy units.
The original {e40k} rules do not appear to allow this.

.The proposal
Define charge move rules that allow you to move your War Engine unit into base contact with multiple enemy units.
We base this option around the idea of War Engine units being able to barge aside smaller units.
****

---

. As in the standard assault move rules, move your War Engine into base contact with the nearest enemy unit.
. Rather than stop there, you may continue to move the War Engine if it has more movement available.
. You *must* stop the move as soon as any of these events occur:
 * The War Engine has run out of available movement.
 * The War Engine has made base contact with a number of enemy units equal to half its initial Damage Capacity.
 * The War Engine has made base contact with an enemy War Engine.
 * The War Engine has moved 5 cm from the first contact with an enemy unit.
. After you end your assault move, your opponent must place their units that your War Engine is barging aside.
They must place these units:
 * in base contact with your War Engine
 * as close as possible to their original positions


.Related information
* xref:main-rules:assault-moves-and-charges.adoc[]