= War engine barging

Two experimental options to improve the rules for when you make a charge move with a War Engine unit.

****
.The problem
Often, when you make a charge move with your War Engine unit, you'd like to move it into base contact with multiple enemy units.
The rules do not actually explain how this should work. 

.The proposal
Define charge move rules that explain how you can move your War Engine unit into base contact with multiple enemy units.
We base these options around the idea that a massive war engine should be able to barge past lesser units to some extent, to get deeper into an enemy detachment and so make contact with more units.
****

---

When it charges, a war engine can barge some enemy units aside and plough deeper into the enemy line.

So, when you make a charge move with a War Engine unit, use the procedure below.

(But be consistent -- you and your opponent should both agree and use either option A or option B for your entire game.)

NOTE: You may *not* barge aside enemy War Engine units.
We consider them to be too massive and dangerous for this to be a viable manoeuvre.

.Option A and B
. As in the standard assault move rules, move your War Engine into base contact with the closest enemy unit.

.Option A: Barging based on initial Damage Capacity (DC)
[start=2]
. Rather than stop there, you may continue your move if you have more movement available.
. You may not continue your move past the point at which you run out of available movement or the War Engine has made contact with a number of enemy units equal to half its initial Damage Capacity -- whichever happens first.

.Option B: Barging based on distance (5 cm)
[start=2]
. Rather than stop there, you may move your War Engine up to a further 5 cm, or the remainder of its available move -- whichever is the least.
 * Remember that a War Engine unit can attack or be attacked by no more units than the number equal to half its initial Damage Capacity. So, you must end your assault move if you reach this condition before you run out of movement.
. (Go to the next step.)

.Option A and B
[start=4]
. After you end your assault move, your opponent must place their units that your War Engine is barging aside.
They must place these units:
 * in base contact with your War Engine
 * as close as possible to their original positions

.Related information
* xref:main-rules:assault-moves-and-charges.adoc[]